// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Thu May  7 00:51:28 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 123776
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "100" [Number of training cycles]
HiddenLayers: "N+20" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,225]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,5]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,8]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[26][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][26];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 26; fWeights[1] = new double[26]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.215364401623885;
   fWeightMatrix0to1[1][0] = 8.60977309928765;
   fWeightMatrix0to1[2][0] = 2.35530914128803;
   fWeightMatrix0to1[3][0] = 1.61937063131941;
   fWeightMatrix0to1[4][0] = -0.70416724239105;
   fWeightMatrix0to1[5][0] = -3.78006551557199;
   fWeightMatrix0to1[6][0] = -0.93253440569455;
   fWeightMatrix0to1[7][0] = 3.06807744616549;
   fWeightMatrix0to1[8][0] = -2.72830089366185;
   fWeightMatrix0to1[9][0] = -0.618991705964308;
   fWeightMatrix0to1[10][0] = -1.18222754012688;
   fWeightMatrix0to1[11][0] = -1.21862000433253;
   fWeightMatrix0to1[12][0] = -1.3166448411787;
   fWeightMatrix0to1[13][0] = -0.837327200456602;
   fWeightMatrix0to1[14][0] = -1.10313103469453;
   fWeightMatrix0to1[15][0] = 3.19751464985458;
   fWeightMatrix0to1[16][0] = -0.421613999758633;
   fWeightMatrix0to1[17][0] = 5.89115142802584;
   fWeightMatrix0to1[18][0] = -0.36469984571866;
   fWeightMatrix0to1[19][0] = 10.3509834877822;
   fWeightMatrix0to1[20][0] = -0.670578795409877;
   fWeightMatrix0to1[21][0] = -0.95963114959391;
   fWeightMatrix0to1[22][0] = 0.362338349186675;
   fWeightMatrix0to1[23][0] = -0.844184243770354;
   fWeightMatrix0to1[24][0] = -0.0989628817454046;
   fWeightMatrix0to1[0][1] = 0.399674138603572;
   fWeightMatrix0to1[1][1] = 2.64112268967328;
   fWeightMatrix0to1[2][1] = -1.88881428901425;
   fWeightMatrix0to1[3][1] = -1.82621070083587;
   fWeightMatrix0to1[4][1] = 0.658403090038356;
   fWeightMatrix0to1[5][1] = -0.524704649952855;
   fWeightMatrix0to1[6][1] = 2.51823951502985;
   fWeightMatrix0to1[7][1] = 1.41456647266862;
   fWeightMatrix0to1[8][1] = -1.00444390937151;
   fWeightMatrix0to1[9][1] = 0.687025228000397;
   fWeightMatrix0to1[10][1] = 0.657335194743675;
   fWeightMatrix0to1[11][1] = -1.62326200675874;
   fWeightMatrix0to1[12][1] = 1.94482190935886;
   fWeightMatrix0to1[13][1] = -1.0859539366228;
   fWeightMatrix0to1[14][1] = 2.4851119395005;
   fWeightMatrix0to1[15][1] = 6.14424777901232;
   fWeightMatrix0to1[16][1] = 1.15796750038431;
   fWeightMatrix0to1[17][1] = 3.09316774005433;
   fWeightMatrix0to1[18][1] = 1.11773436112937;
   fWeightMatrix0to1[19][1] = -4.74394983195933;
   fWeightMatrix0to1[20][1] = -1.11189294865192;
   fWeightMatrix0to1[21][1] = 1.46613684711726;
   fWeightMatrix0to1[22][1] = 0.312246247354033;
   fWeightMatrix0to1[23][1] = 1.56723859685612;
   fWeightMatrix0to1[24][1] = 2.5636173317897;
   fWeightMatrix0to1[0][2] = 2.05962172087372;
   fWeightMatrix0to1[1][2] = 1.09676363425017;
   fWeightMatrix0to1[2][2] = -4.32101441466262;
   fWeightMatrix0to1[3][2] = 1.36003937543322;
   fWeightMatrix0to1[4][2] = -3.68222000575952;
   fWeightMatrix0to1[5][2] = -1.80010761614183;
   fWeightMatrix0to1[6][2] = -0.947889619792679;
   fWeightMatrix0to1[7][2] = -1.38857394092292;
   fWeightMatrix0to1[8][2] = 1.1541564078097;
   fWeightMatrix0to1[9][2] = 0.793646162541932;
   fWeightMatrix0to1[10][2] = -0.891897844082752;
   fWeightMatrix0to1[11][2] = 0.744981527553604;
   fWeightMatrix0to1[12][2] = -0.128950967292422;
   fWeightMatrix0to1[13][2] = 1.56259796365052;
   fWeightMatrix0to1[14][2] = 4.58814873269952;
   fWeightMatrix0to1[15][2] = -0.870578480896718;
   fWeightMatrix0to1[16][2] = 0.647014087233305;
   fWeightMatrix0to1[17][2] = -3.10293950042246;
   fWeightMatrix0to1[18][2] = 0.836779022693558;
   fWeightMatrix0to1[19][2] = -11.3384909423696;
   fWeightMatrix0to1[20][2] = 0.0854323919331616;
   fWeightMatrix0to1[21][2] = -0.237176539257028;
   fWeightMatrix0to1[22][2] = 1.15726096781553;
   fWeightMatrix0to1[23][2] = 10.6397038426746;
   fWeightMatrix0to1[24][2] = 3.61510357760141;
   fWeightMatrix0to1[0][3] = 0.738956302747524;
   fWeightMatrix0to1[1][3] = -3.60315274643506;
   fWeightMatrix0to1[2][3] = 0.36424510906006;
   fWeightMatrix0to1[3][3] = 1.05800332939287;
   fWeightMatrix0to1[4][3] = 2.40537378983794;
   fWeightMatrix0to1[5][3] = 2.5372689169724;
   fWeightMatrix0to1[6][3] = 1.32347673792034;
   fWeightMatrix0to1[7][3] = 2.52857306048837;
   fWeightMatrix0to1[8][3] = -0.283554077696648;
   fWeightMatrix0to1[9][3] = 0.00901280725301696;
   fWeightMatrix0to1[10][3] = 1.73248607560203;
   fWeightMatrix0to1[11][3] = 2.20051602891165;
   fWeightMatrix0to1[12][3] = -0.627068334702524;
   fWeightMatrix0to1[13][3] = -0.426401459890108;
   fWeightMatrix0to1[14][3] = -0.506840196619854;
   fWeightMatrix0to1[15][3] = 1.11445602461947;
   fWeightMatrix0to1[16][3] = 0.673403774532387;
   fWeightMatrix0to1[17][3] = 2.58453298838605;
   fWeightMatrix0to1[18][3] = -0.88849022652808;
   fWeightMatrix0to1[19][3] = 1.03764881187088;
   fWeightMatrix0to1[20][3] = 3.49390555038301;
   fWeightMatrix0to1[21][3] = 0.711738347332313;
   fWeightMatrix0to1[22][3] = -0.368394382522251;
   fWeightMatrix0to1[23][3] = -2.47160104740003;
   fWeightMatrix0to1[24][3] = -0.112725174813537;
   fWeightMatrix0to1[0][4] = -0.288852824528975;
   fWeightMatrix0to1[1][4] = -2.01282135274518;
   fWeightMatrix0to1[2][4] = 2.64537719191106;
   fWeightMatrix0to1[3][4] = 1.72689897765927;
   fWeightMatrix0to1[4][4] = 1.01190922444365;
   fWeightMatrix0to1[5][4] = 3.25758226134114;
   fWeightMatrix0to1[6][4] = -0.3743632562969;
   fWeightMatrix0to1[7][4] = 0.951221021318766;
   fWeightMatrix0to1[8][4] = 0.856110888313122;
   fWeightMatrix0to1[9][4] = 1.38947101673999;
   fWeightMatrix0to1[10][4] = 0.530428094417807;
   fWeightMatrix0to1[11][4] = 2.19995933574871;
   fWeightMatrix0to1[12][4] = 0.769790668147694;
   fWeightMatrix0to1[13][4] = 1.84791579845883;
   fWeightMatrix0to1[14][4] = -0.231346428668128;
   fWeightMatrix0to1[15][4] = 2.44731234389374;
   fWeightMatrix0to1[16][4] = 1.29139476688203;
   fWeightMatrix0to1[17][4] = 0.330268349934454;
   fWeightMatrix0to1[18][4] = 1.85236063436593;
   fWeightMatrix0to1[19][4] = 2.30829825599963;
   fWeightMatrix0to1[20][4] = 0.0117093612799082;
   fWeightMatrix0to1[21][4] = 1.83846359722479;
   fWeightMatrix0to1[22][4] = 1.00976656729131;
   fWeightMatrix0to1[23][4] = 0.397090110433982;
   fWeightMatrix0to1[24][4] = 0.683341965917151;
   fWeightMatrix0to1[0][5] = -1.75604868346638;
   fWeightMatrix0to1[1][5] = -1.26970136095929;
   fWeightMatrix0to1[2][5] = -1.74255905607606;
   fWeightMatrix0to1[3][5] = -1.8822927084439;
   fWeightMatrix0to1[4][5] = -1.99829535805286;
   fWeightMatrix0to1[5][5] = 0.725480352955988;
   fWeightMatrix0to1[6][5] = -2.3616272117658;
   fWeightMatrix0to1[7][5] = -1.44925761768958;
   fWeightMatrix0to1[8][5] = -2.8116938662976;
   fWeightMatrix0to1[9][5] = -1.15816063740032;
   fWeightMatrix0to1[10][5] = -1.52567039120275;
   fWeightMatrix0to1[11][5] = 0.382531121612123;
   fWeightMatrix0to1[12][5] = -2.45953892615294;
   fWeightMatrix0to1[13][5] = -1.32506671842916;
   fWeightMatrix0to1[14][5] = 0.498602909180767;
   fWeightMatrix0to1[15][5] = 0.663100711287954;
   fWeightMatrix0to1[16][5] = -0.825991242617466;
   fWeightMatrix0to1[17][5] = -3.51622742161421;
   fWeightMatrix0to1[18][5] = -1.31473638996807;
   fWeightMatrix0to1[19][5] = -7.9348864895786;
   fWeightMatrix0to1[20][5] = -0.690382117802285;
   fWeightMatrix0to1[21][5] = -0.720501217932348;
   fWeightMatrix0to1[22][5] = -1.95378746951914;
   fWeightMatrix0to1[23][5] = 3.67033669933133;
   fWeightMatrix0to1[24][5] = 0.232260510783896;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.135793784804894;
   fWeightMatrix1to2[0][1] = 0.993012375106827;
   fWeightMatrix1to2[0][2] = 0.977805012068542;
   fWeightMatrix1to2[0][3] = 0.396348256105774;
   fWeightMatrix1to2[0][4] = -0.0139134576563705;
   fWeightMatrix1to2[0][5] = 1.30985353943287;
   fWeightMatrix1to2[0][6] = 0.954049818095406;
   fWeightMatrix1to2[0][7] = 0.293967159790442;
   fWeightMatrix1to2[0][8] = -0.152909770251294;
   fWeightMatrix1to2[0][9] = -0.0501992784356093;
   fWeightMatrix1to2[0][10] = -0.00114022072878755;
   fWeightMatrix1to2[0][11] = -0.875854644519715;
   fWeightMatrix1to2[0][12] = 0.0520641535008727;
   fWeightMatrix1to2[0][13] = -0.164643381309272;
   fWeightMatrix1to2[0][14] = -1.06521847065814;
   fWeightMatrix1to2[0][15] = -1.26721781962355;
   fWeightMatrix1to2[0][16] = 0.204403922939891;
   fWeightMatrix1to2[0][17] = 1.89317392747905;
   fWeightMatrix1to2[0][18] = -0.234106015349549;
   fWeightMatrix1to2[0][19] = -1.35188194405297;
   fWeightMatrix1to2[0][20] = -0.472596270864607;
   fWeightMatrix1to2[0][21] = 0.256996986920522;
   fWeightMatrix1to2[0][22] = 0.133614649459428;
   fWeightMatrix1to2[0][23] = 1.31330797261857;
   fWeightMatrix1to2[0][24] = -1.07993114674627;
   fWeightMatrix1to2[0][25] = -0.465878297663552;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 250;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 225;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 184;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 225;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 5;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 4;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 5;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 8;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 8;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 8;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
