// Class: ReadHMatrix
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : HMatrix::HMatrix
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sat May 16 19:12:49 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/GIT/Diabetic/train_tree
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Expression 2                                                    'F'    [0,252]
Blue                          Blue                          Blue                          Variable 3                    units                             'F'    [0,233]
PixelX                        PixelX                        PixelX                        Variable 4                    units                             'F'    [36,548]
PixelY                        PixelY                        PixelY                        Variable 5                    units                             'F'    [0,388]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadHMatrix : public IClassifierReader {

 public:

   // constructor
   ReadHMatrix( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadHMatrix" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "PixelX", "PixelY" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadHMatrix() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // arrays of input evt vs. variable 
   double fInvHMatrixS[5][5]; // inverse H-matrix (signal)
   double fInvHMatrixB[5][5]; // inverse H-matrix (background)
   double fVecMeanS[5];    // vector of mean values (signal)
   double fVecMeanB[5];    // vector of mean values (background)
   
   double GetChi2( const std::vector<double>& inputValues, int type ) const;
};
   
void ReadHMatrix::Initialize() 
{
   // init vectors with mean values
   fVecMeanS[0] = 130.323666666667;
   fVecMeanB[0] = 117.259666666667;
   fVecMeanS[1] = 95.365;
   fVecMeanB[1] = 80.883;
   fVecMeanS[2] = 57.4416666666667;
   fVecMeanB[2] = 59.6076666666667;
   fVecMeanS[3] = 259.938666666667;
   fVecMeanB[3] = 293.316333333333;
   fVecMeanS[4] = 173.263333333333;
   fVecMeanB[4] = 194.176333333333;
   
   // init H-matrices
   fInvHMatrixS[0][0] = 0.024235056363678;
   fInvHMatrixB[0][0] = 0.00452908459429762;
   fInvHMatrixS[0][1] = -0.0447286325616606;
   fInvHMatrixB[0][1] = -0.0100077613100619;
   fInvHMatrixS[0][2] = 0.0282271010528002;
   fInvHMatrixB[0][2] = 0.00507377350335602;
   fInvHMatrixS[0][3] = -0.000536178277380762;
   fInvHMatrixB[0][3] = -0.000174638367878026;
   fInvHMatrixS[0][4] = -0.000360912631943211;
   fInvHMatrixB[0][4] = 8.51099227990101e-07;
   fInvHMatrixS[1][0] = -0.0447286325616606;
   fInvHMatrixB[1][0] = -0.0100077613100619;
   fInvHMatrixS[1][1] = 0.0961459793231728;
   fInvHMatrixB[1][1] = 0.0292341585230275;
   fInvHMatrixS[1][2] = -0.0712987598945603;
   fInvHMatrixB[1][2] = -0.0174333708978027;
   fInvHMatrixS[1][3] = 0.00173346478981942;
   fInvHMatrixB[1][3] = 0.000609421555432252;
   fInvHMatrixS[1][4] = 0.000289511192046835;
   fInvHMatrixB[1][4] = 9.86472025543597e-05;
   fInvHMatrixS[2][0] = 0.0282271010528002;
   fInvHMatrixB[2][0] = 0.00507377350335602;
   fInvHMatrixS[2][1] = -0.0712987598945603;
   fInvHMatrixB[2][1] = -0.0174333708978027;
   fInvHMatrixS[2][2] = 0.0644126198024131;
   fInvHMatrixB[2][2] = 0.0121219225086443;
   fInvHMatrixS[2][3] = -0.00226907453296709;
   fInvHMatrixB[2][3] = -0.000311921988603168;
   fInvHMatrixS[2][4] = 0.000361408737520201;
   fInvHMatrixB[2][4] = -4.32890121582671e-05;
   fInvHMatrixS[3][0] = -0.000536178277380762;
   fInvHMatrixB[3][0] = -0.000174638367878026;
   fInvHMatrixS[3][1] = 0.00173346478981942;
   fInvHMatrixB[3][1] = 0.000609421555432253;
   fInvHMatrixS[3][2] = -0.00226907453296709;
   fInvHMatrixB[3][2] = -0.000311921988603168;
   fInvHMatrixS[3][3] = 0.000287536667299615;
   fInvHMatrixB[3][3] = 7.56319587307502e-05;
   fInvHMatrixS[3][4] = -4.51766431971811e-05;
   fInvHMatrixB[3][4] = 5.5403037590138e-06;
   fInvHMatrixS[4][0] = -0.000360912631943211;
   fInvHMatrixB[4][0] = 8.51099227990105e-07;
   fInvHMatrixS[4][1] = 0.000289511192046836;
   fInvHMatrixB[4][1] = 9.86472025543596e-05;
   fInvHMatrixS[4][2] = 0.000361408737520201;
   fInvHMatrixB[4][2] = -4.32890121582671e-05;
   fInvHMatrixS[4][3] = -4.51766431971811e-05;
   fInvHMatrixB[4][3] = 5.5403037590138e-06;
   fInvHMatrixS[4][4] = 0.000194709888131777;
   fInvHMatrixB[4][4] = 9.05014222750875e-05;
}
   
inline double ReadHMatrix::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   // returns the H-matrix signal estimator
   std::vector<double> inputValuesSig = inputValues;
   std::vector<double> inputValuesBgd = inputValues;
   double s = GetChi2( inputValuesSig, 0 );
   double b = GetChi2( inputValuesBgd, 1 );
   
   if (s+b <= 0) std::cout << "Problem in class ReadHMatrix::GetMvaValue__: s+b = "
                           << s+b << " <= 0 "  << std::endl;
   
   return (b - s)/(s + b);
}
   
inline double ReadHMatrix::GetChi2( const std::vector<double>& inputValues, int type ) const
{
   // compute chi2-estimator for event according to type (signal/background)
   
   size_t ivar,jvar;
   double chi2 = 0;
   for (ivar=0; ivar<GetNvar(); ivar++) {
      for (jvar=0; jvar<GetNvar(); jvar++) {
         if (type == 0) 
            chi2 += ( (inputValues[ivar] - fVecMeanS[ivar])*(inputValues[jvar] - fVecMeanS[jvar])
                      * fInvHMatrixS[ivar][jvar] );
         else
            chi2 += ( (inputValues[ivar] - fVecMeanB[ivar])*(inputValues[jvar] - fVecMeanB[jvar])
                      * fInvHMatrixB[ivar][jvar] );
      }
   }   // loop over variables   
   
   // sanity check
   if (chi2 < 0) std::cout << "Problem in class ReadHMatrix::GetChi2: chi2 = "
                           << chi2 << " < 0 "  << std::endl;
   
   return chi2;
}
   
// Clean up
inline void ReadHMatrix::Clear() 
{
   // nothing to clear
}
   inline double ReadHMatrix::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
