// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sat May 16 19:26:03 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/GIT/Diabetic/train_tree
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Expression 2                                                    'F'    [0,252]
Blue                          Blue                          Blue                          Variable 3                    units                             'F'    [0,233]
PixelX                        PixelX                        PixelX                        Variable 4                    units                             'F'    [36,548]
PixelY                        PixelY                        PixelY                        Variable 5                    units                             'F'    [0,388]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "PixelX", "PixelY" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=-0.1212216383;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[2]<77.66666412)&&(inputValues[3]<377.3333435)&&(inputValues[4]<314.0952454)) rval+=0.4510910953;   // importance = 0.148
   if ((97.14286041<inputValues[0])&&(inputValues[1]<85.04762268)&&(inputValues[2]<74.52381134)&&(inputValues[4]<267.7619019)) rval+=-0.5298928237;   // importance = 0.148
   if ((inputValues[2]<44.38095093)) rval+=-0.3855703358;   // importance = 0.123
   if ((121.4285736<inputValues[0])&&(inputValues[1]<103.4285736)) rval+=-0.3332335969;   // importance = 0.098
   if ((97.14286041<inputValues[0])&&(85.04762268<inputValues[1])&&(inputValues[2]<74.52381134)&&(inputValues[4]<267.7619019)) rval+=0.2962534455;   // importance = 0.087
   if ((101.3333359<inputValues[1])&&(inputValues[2]<88.76190186)) rval+=0.3060615746;   // importance = 0.083
   if ((inputValues[0]<145.7142792)&&(122.9047623<inputValues[3])&&(inputValues[3]<401.7142944)) rval+=0.161738018;   // importance = 0.054
   if ((77.66666412<inputValues[2])&&(inputValues[3]<309)) rval+=-0.2163384536;   // importance = 0.048
   if ((77.66666412<inputValues[2])) rval+=-0.1493742008;   // importance = 0.039
   if ((inputValues[1]<84)&&(272.8095093<inputValues[3])) rval+=-0.1342947279;   // importance = 0.038
   if ((86.2857132<inputValues[1])&&(44.38095093<inputValues[2])) rval+=0.08876052213;   // importance = 0.029
   if ((101.3333359<inputValues[1])&&(58.66666794<inputValues[2])&&(inputValues[2]<88.76190186)) rval+=0.07203235689;   // importance = 0.019
   if ((inputValues[0]<145.7142792)&&(inputValues[3]<401.7142944)) rval+=0.04267781668;   // importance = 0.014
   if ((inputValues[2]<66.57142639)&&(184.7619019<inputValues[4])) rval+=0.04049793713;   // importance = 0.013
   if ((97.14286041<inputValues[0])&&(inputValues[4]<267.7619019)) rval+=-0.03960021458;   // importance = 0.012
   if ((206.6666718<inputValues[3])) rval+=0.03623862159;   // importance = 0.011
   if ((127.8571396<inputValues[0])&&(inputValues[2]<55.47618866)&&(inputValues[4]<160.4761963)) rval+=-0.06667236341;   // importance = 0.011
   if ((73.85713959<inputValues[1])&&(inputValues[2]<77.66666412)&&(inputValues[3]<311.4285583)) rval+=-0.02754341746;   // importance = 0.009
   if ((inputValues[0]<145.7142792)) rval+=0.02993696897;   // importance = 0.009
   if ((121.4285736<inputValues[0])) rval+=-0.02558402339;   // importance = 0.008
   if ((inputValues[1]<120)) rval+=-0.03159038013;   // importance = 0.007
   if ((129.3333282<inputValues[4])) rval+=0.01827763943;   // importance = 0.006
   if ((97.14286041<inputValues[0])&&(74.52381134<inputValues[2])&&(inputValues[4]<267.7619019)) rval+=-0.02065107505;   // importance = 0.005
   if ((inputValues[4]<129.3333282)) rval+=-0.01348613732;   // importance = 0.004
   if ((inputValues[0]<127.8571396)&&(inputValues[2]<55.47618866)) rval+=0.007680563396;   // importance = 0.002
   if ((72<inputValues[1])&&(inputValues[4]<129.3333282)) rval+=-0.005887037784;   // importance = 0.002
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=0.003596220853*std::min( double(186), std::max( double(inputValues[0]), double(7)));   // importance = 0.078
   rval+=0.05255976007*std::min( double(147), std::max( double(inputValues[1]), double(9)));   // importance = 0.938
   rval+=-0.06316185096*std::min( double(123), std::max( double(inputValues[2]), double(7)));   // importance = 1.000
   rval+=-0.0018813694*std::min( double(504), std::max( double(inputValues[3]), double(85)));   // importance = 0.128
   rval+=-0.003149762431*std::min( double(364), std::max( double(inputValues[4]), double(22)));   // importance = 0.182
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
