// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Mon May 18 00:11:35 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/GIT/Diabetic/train_tree
Training events: 107225
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,230]
Green*Blue/Red                Green_T_Blue_D_Red            Green*Blue/Red                Green*Blue/Red                                                  'F'    [0,1512]
(Blue+Green)/Red              _Blue_P_Green__D_Red          (Blue+Green)/Red              (Blue+Green)/Red                                                'F'    [0,78]
(Blue-Green)/Red              _Blue_M_Green__D_Red          (Blue-Green)/Red              (Blue-Green)/Red                                                'F'    [-10,18]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "Green*Blue/Red", "(Blue+Green)/Red", "(Blue-Green)/Red" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[12][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -3.56841476233405;
   fWeightMatrix0to1[1][0] = 1.7521020951949;
   fWeightMatrix0to1[2][0] = 4.96932730239802;
   fWeightMatrix0to1[3][0] = 0.709969126176599;
   fWeightMatrix0to1[4][0] = -1.8070294218713;
   fWeightMatrix0to1[5][0] = -1.84100650703264;
   fWeightMatrix0to1[6][0] = -1.39316221136363;
   fWeightMatrix0to1[7][0] = 4.91177131395246;
   fWeightMatrix0to1[8][0] = -7.85490562468036;
   fWeightMatrix0to1[9][0] = -2.04077759809118;
   fWeightMatrix0to1[10][0] = -0.304452920862837;
   fWeightMatrix0to1[0][1] = -0.236792536448373;
   fWeightMatrix0to1[1][1] = -1.02061508283939;
   fWeightMatrix0to1[2][1] = -4.04259866761267;
   fWeightMatrix0to1[3][1] = -0.4012509373266;
   fWeightMatrix0to1[4][1] = 0.85049871949905;
   fWeightMatrix0to1[5][1] = 1.23442129319148;
   fWeightMatrix0to1[6][1] = 0.370651672124378;
   fWeightMatrix0to1[7][1] = 1.09526912012882;
   fWeightMatrix0to1[8][1] = 2.52643309817018;
   fWeightMatrix0to1[9][1] = -0.594487121002594;
   fWeightMatrix0to1[10][1] = -3.8412298183687;
   fWeightMatrix0to1[0][2] = -0.202100144784459;
   fWeightMatrix0to1[1][2] = 0.125432926957092;
   fWeightMatrix0to1[2][2] = -5.07316444618765;
   fWeightMatrix0to1[3][2] = -3.40497606211196;
   fWeightMatrix0to1[4][2] = 1.65576090071797;
   fWeightMatrix0to1[5][2] = -3.75266183268249;
   fWeightMatrix0to1[6][2] = -1.68743140106912;
   fWeightMatrix0to1[7][2] = -0.779104719556159;
   fWeightMatrix0to1[8][2] = 15.1978757860284;
   fWeightMatrix0to1[9][2] = 0.594175384250811;
   fWeightMatrix0to1[10][2] = 0.134882991207748;
   fWeightMatrix0to1[0][3] = -1.60643468002559;
   fWeightMatrix0to1[1][3] = -0.441057114277489;
   fWeightMatrix0to1[2][3] = -0.103282923328976;
   fWeightMatrix0to1[3][3] = -1.96339604736949;
   fWeightMatrix0to1[4][3] = 1.69741528155272;
   fWeightMatrix0to1[5][3] = -1.76144126125339;
   fWeightMatrix0to1[6][3] = 0.889980366381189;
   fWeightMatrix0to1[7][3] = 1.8566591773855;
   fWeightMatrix0to1[8][3] = -2.4793103899459;
   fWeightMatrix0to1[9][3] = 2.37083640661681;
   fWeightMatrix0to1[10][3] = 4.33749166364954;
   fWeightMatrix0to1[0][4] = -2.35423945069836;
   fWeightMatrix0to1[1][4] = -2.92961387566172;
   fWeightMatrix0to1[2][4] = 2.39900918260352;
   fWeightMatrix0to1[3][4] = -0.300582986019408;
   fWeightMatrix0to1[4][4] = 1.32969365971802;
   fWeightMatrix0to1[5][4] = 0.731919934168587;
   fWeightMatrix0to1[6][4] = 4.31050418435718;
   fWeightMatrix0to1[7][4] = 2.1914629925188;
   fWeightMatrix0to1[8][4] = -1.20133234903149;
   fWeightMatrix0to1[9][4] = 0.898666974571159;
   fWeightMatrix0to1[10][4] = -4.66469729592992;
   fWeightMatrix0to1[0][5] = -0.537381485567746;
   fWeightMatrix0to1[1][5] = -1.52779274286461;
   fWeightMatrix0to1[2][5] = -1.05522355095359;
   fWeightMatrix0to1[3][5] = 0.671699162352639;
   fWeightMatrix0to1[4][5] = 0.60682072204634;
   fWeightMatrix0to1[5][5] = -0.835513282689209;
   fWeightMatrix0to1[6][5] = 0.48713689282332;
   fWeightMatrix0to1[7][5] = 0.064781883753824;
   fWeightMatrix0to1[8][5] = 2.07962853660746;
   fWeightMatrix0to1[9][5] = 1.07198303990034;
   fWeightMatrix0to1[10][5] = -0.499507522297888;
   fWeightMatrix0to1[0][6] = 0.206144241679123;
   fWeightMatrix0to1[1][6] = -0.497473665875434;
   fWeightMatrix0to1[2][6] = -2.36448761456232;
   fWeightMatrix0to1[3][6] = 0.620147303644018;
   fWeightMatrix0to1[4][6] = -0.909314885248645;
   fWeightMatrix0to1[5][6] = -5.86838215341712;
   fWeightMatrix0to1[6][6] = 2.0849754357296;
   fWeightMatrix0to1[7][6] = -0.547985162342308;
   fWeightMatrix0to1[8][6] = 6.19565586133109;
   fWeightMatrix0to1[9][6] = 0.31524733528359;
   fWeightMatrix0to1[10][6] = -5.15338853541684;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.87053927040067;
   fWeightMatrix1to2[0][1] = 0.752758610685892;
   fWeightMatrix1to2[0][2] = 0.183810121852755;
   fWeightMatrix1to2[0][3] = 1.10223957260226;
   fWeightMatrix1to2[0][4] = 0.00906863766397221;
   fWeightMatrix1to2[0][5] = 2.11190791862057;
   fWeightMatrix1to2[0][6] = -0.82337483248649;
   fWeightMatrix1to2[0][7] = -0.82029263764578;
   fWeightMatrix1to2[0][8] = 0.667153964003601;
   fWeightMatrix1to2[0][9] = 1.49088470407346;
   fWeightMatrix1to2[0][10] = -3.09839205403496;
   fWeightMatrix1to2[0][11] = -0.593448307470446;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 253;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 204;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 230;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 230;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 1512;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 230;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 1512;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 78;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 8;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 78;
   fMin_1[0][5] = -10;
   fMax_1[0][5] = 18;
   fMin_1[1][5] = -1.5;
   fMax_1[1][5] = 5;
   fMin_1[2][5] = -10;
   fMax_1[2][5] = 18;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
