// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Tue May 12 00:03:09 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/GIT/Diabetic/macros
Training events: 1772524
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,255]
Hue                           Hue                           Hue                           Hue                                                             'F'    [0,300]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,34]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,55]
PixelX                        PixelX                        PixelX                        PixelX                                                          'F'    [0,428]
PixelY                        PixelY                        PixelY                        PixelY                                                          'F'    [0,316]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "Hue", "GreenOverRed", "BlueOverRed", "PixelX", "PixelY" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[10][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[9][10];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][9];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 10; fWeights[1] = new double[10]; 
   fLayerSize[2] = 9; fWeights[2] = new double[9]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.561334106788967;
   fWeightMatrix0to1[1][0] = 1.30807940927931;
   fWeightMatrix0to1[2][0] = 0.833539789327722;
   fWeightMatrix0to1[3][0] = 3.56256790311321;
   fWeightMatrix0to1[4][0] = -1.91541895477152;
   fWeightMatrix0to1[5][0] = -2.85513435095987;
   fWeightMatrix0to1[6][0] = -1.70444221648813;
   fWeightMatrix0to1[7][0] = 0.992644102765719;
   fWeightMatrix0to1[8][0] = -2.37218038509362;
   fWeightMatrix0to1[0][1] = -1.182795271218;
   fWeightMatrix0to1[1][1] = -2.39113067300812;
   fWeightMatrix0to1[2][1] = -0.62926501722429;
   fWeightMatrix0to1[3][1] = 1.0436526183618;
   fWeightMatrix0to1[4][1] = -0.510849853994663;
   fWeightMatrix0to1[5][1] = -2.55537389093358;
   fWeightMatrix0to1[6][1] = -2.4753896455544;
   fWeightMatrix0to1[7][1] = -2.41208859528051;
   fWeightMatrix0to1[8][1] = 0.312331973443035;
   fWeightMatrix0to1[0][2] = 0.222480338057885;
   fWeightMatrix0to1[1][2] = 1.43348927943428;
   fWeightMatrix0to1[2][2] = -0.00258028838116525;
   fWeightMatrix0to1[3][2] = 1.0712758709627;
   fWeightMatrix0to1[4][2] = 0.647408611500813;
   fWeightMatrix0to1[5][2] = 0.354835486704524;
   fWeightMatrix0to1[6][2] = -4.69462927986311;
   fWeightMatrix0to1[7][2] = -1.59787054145802;
   fWeightMatrix0to1[8][2] = 1.45103705027319;
   fWeightMatrix0to1[0][3] = 0.0228751058750687;
   fWeightMatrix0to1[1][3] = -3.02657152882596;
   fWeightMatrix0to1[2][3] = 0.0682440231619081;
   fWeightMatrix0to1[3][3] = 1.56813470464157;
   fWeightMatrix0to1[4][3] = 1.18151704251974;
   fWeightMatrix0to1[5][3] = -0.583818609350397;
   fWeightMatrix0to1[6][3] = -0.738633661165204;
   fWeightMatrix0to1[7][3] = 0.219042999979919;
   fWeightMatrix0to1[8][3] = 0.355874191446765;
   fWeightMatrix0to1[0][4] = -1.0986015040893;
   fWeightMatrix0to1[1][4] = 2.2074371725687;
   fWeightMatrix0to1[2][4] = -0.81592070957075;
   fWeightMatrix0to1[3][4] = 0.750746885977112;
   fWeightMatrix0to1[4][4] = 1.28992152101096;
   fWeightMatrix0to1[5][4] = 0.298482366560834;
   fWeightMatrix0to1[6][4] = 2.72765862673058;
   fWeightMatrix0to1[7][4] = 1.38261696583427;
   fWeightMatrix0to1[8][4] = -0.740834823651443;
   fWeightMatrix0to1[0][5] = -1.30755930372708;
   fWeightMatrix0to1[1][5] = 1.35314198377617;
   fWeightMatrix0to1[2][5] = 0.524267728976994;
   fWeightMatrix0to1[3][5] = 1.15837659711977;
   fWeightMatrix0to1[4][5] = 1.56767966511485;
   fWeightMatrix0to1[5][5] = 1.34827632407109;
   fWeightMatrix0to1[6][5] = 2.08500893793661;
   fWeightMatrix0to1[7][5] = -1.3300504791082;
   fWeightMatrix0to1[8][5] = 1.50396783571746;
   fWeightMatrix0to1[0][6] = -3.03858837968037;
   fWeightMatrix0to1[1][6] = -0.237105588150182;
   fWeightMatrix0to1[2][6] = -1.52510566794268;
   fWeightMatrix0to1[3][6] = -2.81430622059116;
   fWeightMatrix0to1[4][6] = 1.36615895558043;
   fWeightMatrix0to1[5][6] = -0.549931587606716;
   fWeightMatrix0to1[6][6] = -0.352948215724656;
   fWeightMatrix0to1[7][6] = 1.67785153436717;
   fWeightMatrix0to1[8][6] = -1.65439669334684;
   fWeightMatrix0to1[0][7] = 1.07080328652949;
   fWeightMatrix0to1[1][7] = -0.402205495155851;
   fWeightMatrix0to1[2][7] = -1.04320647019953;
   fWeightMatrix0to1[3][7] = -0.207498267146664;
   fWeightMatrix0to1[4][7] = -1.32179386451759;
   fWeightMatrix0to1[5][7] = 0.126113085645924;
   fWeightMatrix0to1[6][7] = -1.12722802968992;
   fWeightMatrix0to1[7][7] = 1.74659375684013;
   fWeightMatrix0to1[8][7] = -3.15871560215473;
   fWeightMatrix0to1[0][8] = 0.515923843535909;
   fWeightMatrix0to1[1][8] = 0.538778395971475;
   fWeightMatrix0to1[2][8] = 0.849279548805257;
   fWeightMatrix0to1[3][8] = 0.037499686779914;
   fWeightMatrix0to1[4][8] = -2.15901738557695;
   fWeightMatrix0to1[5][8] = -1.65918338148234;
   fWeightMatrix0to1[6][8] = -0.0381324833030693;
   fWeightMatrix0to1[7][8] = 0.132656685079484;
   fWeightMatrix0to1[8][8] = 1.87692487528094;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.275990065056378;
   fWeightMatrix1to2[1][0] = 0.724440215533637;
   fWeightMatrix1to2[2][0] = -1.57874872323634;
   fWeightMatrix1to2[3][0] = -1.56039337518668;
   fWeightMatrix1to2[4][0] = -0.415287386781836;
   fWeightMatrix1to2[5][0] = 1.03143489100577;
   fWeightMatrix1to2[6][0] = -1.88498680590283;
   fWeightMatrix1to2[7][0] = -2.26250284842727;
   fWeightMatrix1to2[0][1] = -2.29022207941144;
   fWeightMatrix1to2[1][1] = -1.23130309007033;
   fWeightMatrix1to2[2][1] = -1.11877847149452;
   fWeightMatrix1to2[3][1] = 0.632587445738244;
   fWeightMatrix1to2[4][1] = -1.44574635964676;
   fWeightMatrix1to2[5][1] = -1.44554347973481;
   fWeightMatrix1to2[6][1] = 0.633597483880531;
   fWeightMatrix1to2[7][1] = -0.61872108189939;
   fWeightMatrix1to2[0][2] = -1.92870906677359;
   fWeightMatrix1to2[1][2] = -1.97145550229683;
   fWeightMatrix1to2[2][2] = -1.15935640428559;
   fWeightMatrix1to2[3][2] = -2.51141381477741;
   fWeightMatrix1to2[4][2] = -1.93254025925656;
   fWeightMatrix1to2[5][2] = 0.246359057608354;
   fWeightMatrix1to2[6][2] = 0.955514867035451;
   fWeightMatrix1to2[7][2] = -1.75633013217466;
   fWeightMatrix1to2[0][3] = 1.29019006145655;
   fWeightMatrix1to2[1][3] = -1.43785356332913;
   fWeightMatrix1to2[2][3] = -1.15943924917899;
   fWeightMatrix1to2[3][3] = -0.555924492936634;
   fWeightMatrix1to2[4][3] = 0.341689017891766;
   fWeightMatrix1to2[5][3] = -3.2486162461197;
   fWeightMatrix1to2[6][3] = -0.375316421705455;
   fWeightMatrix1to2[7][3] = 0.468869770122324;
   fWeightMatrix1to2[0][4] = 0.282088604916908;
   fWeightMatrix1to2[1][4] = -1.53202785159423;
   fWeightMatrix1to2[2][4] = 1.44587581671113;
   fWeightMatrix1to2[3][4] = 0.295458934258292;
   fWeightMatrix1to2[4][4] = -0.920071822616634;
   fWeightMatrix1to2[5][4] = 0.529264761291587;
   fWeightMatrix1to2[6][4] = -1.19857028319569;
   fWeightMatrix1to2[7][4] = -1.51841098372515;
   fWeightMatrix1to2[0][5] = -0.00807975155638066;
   fWeightMatrix1to2[1][5] = -1.27539106942902;
   fWeightMatrix1to2[2][5] = 2.7461542031814;
   fWeightMatrix1to2[3][5] = 0.0070880500903089;
   fWeightMatrix1to2[4][5] = -0.0530042219513914;
   fWeightMatrix1to2[5][5] = -2.16990426717351;
   fWeightMatrix1to2[6][5] = -0.377759836461357;
   fWeightMatrix1to2[7][5] = -1.74617683143288;
   fWeightMatrix1to2[0][6] = 0.954491058463882;
   fWeightMatrix1to2[1][6] = 0.295550542455994;
   fWeightMatrix1to2[2][6] = -2.74760150419086;
   fWeightMatrix1to2[3][6] = 1.09418279838832;
   fWeightMatrix1to2[4][6] = -1.60345647221623;
   fWeightMatrix1to2[5][6] = 1.88693623012049;
   fWeightMatrix1to2[6][6] = 1.12198274684333;
   fWeightMatrix1to2[7][6] = 1.40866793275812;
   fWeightMatrix1to2[0][7] = -1.94148649235872;
   fWeightMatrix1to2[1][7] = -0.218186970235705;
   fWeightMatrix1to2[2][7] = 1.98258272383756;
   fWeightMatrix1to2[3][7] = 1.18350177655211;
   fWeightMatrix1to2[4][7] = -0.0682255987759657;
   fWeightMatrix1to2[5][7] = -1.6208369035349;
   fWeightMatrix1to2[6][7] = -0.68963331481579;
   fWeightMatrix1to2[7][7] = -2.10811397670197;
   fWeightMatrix1to2[0][8] = 1.06880436138457;
   fWeightMatrix1to2[1][8] = 0.482492213955932;
   fWeightMatrix1to2[2][8] = -2.84108726811561;
   fWeightMatrix1to2[3][8] = -2.07065886075459;
   fWeightMatrix1to2[4][8] = -0.0448607271076371;
   fWeightMatrix1to2[5][8] = -2.77715146761421;
   fWeightMatrix1to2[6][8] = -0.919991364364601;
   fWeightMatrix1to2[7][8] = 1.43735989032624;
   fWeightMatrix1to2[0][9] = -0.930082857415117;
   fWeightMatrix1to2[1][9] = -1.01346477694552;
   fWeightMatrix1to2[2][9] = 0.0669646594028952;
   fWeightMatrix1to2[3][9] = 0.0997512916720571;
   fWeightMatrix1to2[4][9] = 0.250008118792856;
   fWeightMatrix1to2[5][9] = 0.374536061906394;
   fWeightMatrix1to2[6][9] = -2.33667495187107;
   fWeightMatrix1to2[7][9] = 0.87115167878749;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.348512819429674;
   fWeightMatrix2to3[0][1] = 1.15530552153202;
   fWeightMatrix2to3[0][2] = -2.21266860518292;
   fWeightMatrix2to3[0][3] = 0.286816483573301;
   fWeightMatrix2to3[0][4] = 0.102124305365487;
   fWeightMatrix2to3[0][5] = 1.85014564521139;
   fWeightMatrix2to3[0][6] = 0.202707668594326;
   fWeightMatrix2to3[0][7] = -0.435957835773513;
   fWeightMatrix2to3[0][8] = -0.0406657429119363;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 255;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 227;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 255;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 300;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 300;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 300;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 34;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 27;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 34;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 50;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 55;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 55;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 428;
   fMin_1[1][6] = 16;
   fMax_1[1][6] = 367;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 428;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 316;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 258;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 316;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
