// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Thu May 14 23:33:39 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/GIT/Diabetic/macros
Training events: 399
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "100" [Number of training cycles]
HiddenLayers: "N+1" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
MeanR                         MeanR                         MeanR                         MeanR                                                           'D'    [5.32279109955,241.066329956]
RMSR                          RMSR                          RMSR                          RMSR                                                            'D'    [3.19233798981,100.793548584]
MeanG                         MeanG                         MeanG                         MeanG                                                           'D'    [5.32279109955,241.066329956]
RMSG                          RMSG                          RMSG                          RMSG                                                            'D'    [3.19233798981,100.793548584]
MeanB                         MeanB                         MeanB                         MeanB                                                           'D'    [5.32279109955,241.066329956]
RMSB                          RMSB                          RMSB                          RMSB                                                            'D'    [3.19233798981,100.793548584]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "MeanR", "RMSR", "MeanG", "RMSG", "MeanB", "RMSB" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.147074655155914;
   fWeightMatrix0to1[1][0] = 1.84253127015382;
   fWeightMatrix0to1[2][0] = 1.2881427419434;
   fWeightMatrix0to1[3][0] = 1.60640011014511;
   fWeightMatrix0to1[4][0] = -1.75975605369972;
   fWeightMatrix0to1[5][0] = -1.39141075681695;
   fWeightMatrix0to1[6][0] = -0.911428624529389;
   fWeightMatrix0to1[0][1] = 1.90046772302856;
   fWeightMatrix0to1[1][1] = -1.12343297529181;
   fWeightMatrix0to1[2][1] = -1.07129605155292;
   fWeightMatrix0to1[3][1] = -1.71481027526039;
   fWeightMatrix0to1[4][1] = -0.337163656161729;
   fWeightMatrix0to1[5][1] = -0.937062920644732;
   fWeightMatrix0to1[6][1] = -0.531341902626224;
   fWeightMatrix0to1[0][2] = -0.432919748584999;
   fWeightMatrix0to1[1][2] = 0.532776199087495;
   fWeightMatrix0to1[2][2] = -0.00608534057935416;
   fWeightMatrix0to1[3][2] = 1.61832695579251;
   fWeightMatrix0to1[4][2] = 0.395053349533546;
   fWeightMatrix0to1[5][2] = 1.48133512497148;
   fWeightMatrix0to1[6][2] = -0.443980819310987;
   fWeightMatrix0to1[0][3] = -0.842600286586396;
   fWeightMatrix0to1[1][3] = 1.03042145722401;
   fWeightMatrix0to1[2][3] = 0.0825406942158649;
   fWeightMatrix0to1[3][3] = -1.26635566146302;
   fWeightMatrix0to1[4][3] = -0.14967498570084;
   fWeightMatrix0to1[5][3] = 1.83036598226444;
   fWeightMatrix0to1[6][3] = -1.16467598331484;
   fWeightMatrix0to1[0][4] = -1.70561226503112;
   fWeightMatrix0to1[1][4] = -0.00855233353377172;
   fWeightMatrix0to1[2][4] = 1.0887148150305;
   fWeightMatrix0to1[3][4] = 1.53201875494888;
   fWeightMatrix0to1[4][4] = -0.0909943607585005;
   fWeightMatrix0to1[5][4] = -0.075089311187952;
   fWeightMatrix0to1[6][4] = 0.114000413801529;
   fWeightMatrix0to1[0][5] = -0.372900058163512;
   fWeightMatrix0to1[1][5] = -1.14890879768094;
   fWeightMatrix0to1[2][5] = 1.74085922312138;
   fWeightMatrix0to1[3][5] = -1.291758724276;
   fWeightMatrix0to1[4][5] = 1.19007038124504;
   fWeightMatrix0to1[5][5] = 1.52087449970112;
   fWeightMatrix0to1[6][5] = 0.780897179903922;
   fWeightMatrix0to1[0][6] = 2.06230469121398;
   fWeightMatrix0to1[1][6] = 1.0555040863496;
   fWeightMatrix0to1[2][6] = -0.698046984212544;
   fWeightMatrix0to1[3][6] = -0.835390220536756;
   fWeightMatrix0to1[4][6] = 0.707728004913871;
   fWeightMatrix0to1[5][6] = 0.340683458140271;
   fWeightMatrix0to1[6][6] = 1.38113176845083;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.30663281810907;
   fWeightMatrix1to2[0][1] = 1.40098017215686;
   fWeightMatrix1to2[0][2] = 1.57967639348614;
   fWeightMatrix1to2[0][3] = -0.793655659001229;
   fWeightMatrix1to2[0][4] = 1.13206734461181;
   fWeightMatrix1to2[0][5] = -1.79386889406737;
   fWeightMatrix1to2[0][6] = -0.912423125442871;
   fWeightMatrix1to2[0][7] = -1.17637503886984;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 38.4629173279;
   fMax_1[0][0] = 241.066329956;
   fMin_1[1][0] = 5.32279109955;
   fMax_1[1][0] = 205.320663452;
   fMin_1[2][0] = 5.32279109955;
   fMax_1[2][0] = 241.066329956;
   fMin_1[0][1] = 16.7193813324;
   fMax_1[0][1] = 79.5716094971;
   fMin_1[1][1] = 3.19233798981;
   fMax_1[1][1] = 100.793548584;
   fMin_1[2][1] = 3.19233798981;
   fMax_1[2][1] = 100.793548584;
   fMin_1[0][2] = 38.4629173279;
   fMax_1[0][2] = 241.066329956;
   fMin_1[1][2] = 5.32279109955;
   fMax_1[1][2] = 205.320663452;
   fMin_1[2][2] = 5.32279109955;
   fMax_1[2][2] = 241.066329956;
   fMin_1[0][3] = 16.7193813324;
   fMax_1[0][3] = 79.5716094971;
   fMin_1[1][3] = 3.19233798981;
   fMax_1[1][3] = 100.793548584;
   fMin_1[2][3] = 3.19233798981;
   fMax_1[2][3] = 100.793548584;
   fMin_1[0][4] = 38.4629173279;
   fMax_1[0][4] = 241.066329956;
   fMin_1[1][4] = 5.32279109955;
   fMax_1[1][4] = 205.320663452;
   fMin_1[2][4] = 5.32279109955;
   fMax_1[2][4] = 241.066329956;
   fMin_1[0][5] = 16.7193813324;
   fMax_1[0][5] = 79.5716094971;
   fMin_1[1][5] = 3.19233798981;
   fMax_1[1][5] = 100.793548584;
   fMin_1[2][5] = 3.19233798981;
   fMax_1[2][5] = 100.793548584;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
