// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sun May 10 09:30:05 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 99147
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "100" [Number of training cycles]
HiddenLayers: "N+10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,226]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,4]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,8]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.747828652372574;
   fWeightMatrix0to1[1][0] = 0.875183024673514;
   fWeightMatrix0to1[2][0] = 2.56876777918028;
   fWeightMatrix0to1[3][0] = 3.2694567671066;
   fWeightMatrix0to1[4][0] = -10.2896026354174;
   fWeightMatrix0to1[5][0] = -8.36355148050677;
   fWeightMatrix0to1[6][0] = 7.93806989574135;
   fWeightMatrix0to1[7][0] = 4.33598430442979;
   fWeightMatrix0to1[8][0] = -2.88904954782964;
   fWeightMatrix0to1[9][0] = -1.15790320198568;
   fWeightMatrix0to1[10][0] = -2.01613155705686;
   fWeightMatrix0to1[11][0] = 1.30511060158637;
   fWeightMatrix0to1[12][0] = -1.16545367715424;
   fWeightMatrix0to1[13][0] = -0.234927779688209;
   fWeightMatrix0to1[14][0] = -0.896956644610157;
   fWeightMatrix0to1[0][1] = 3.57941978464015;
   fWeightMatrix0to1[1][1] = -0.75388613282075;
   fWeightMatrix0to1[2][1] = 0.182931148934773;
   fWeightMatrix0to1[3][1] = -1.69819978936061;
   fWeightMatrix0to1[4][1] = 4.94283130333544;
   fWeightMatrix0to1[5][1] = 4.84493321704198;
   fWeightMatrix0to1[6][1] = -5.32150112998152;
   fWeightMatrix0to1[7][1] = 2.68129302147832;
   fWeightMatrix0to1[8][1] = -6.69824541236776;
   fWeightMatrix0to1[9][1] = -0.581095795221805;
   fWeightMatrix0to1[10][1] = -0.321249367993024;
   fWeightMatrix0to1[11][1] = 3.33674088843735;
   fWeightMatrix0to1[12][1] = -1.35710038936469;
   fWeightMatrix0to1[13][1] = -1.8724441463088;
   fWeightMatrix0to1[14][1] = -0.0838226284458345;
   fWeightMatrix0to1[0][2] = 2.5538603972676;
   fWeightMatrix0to1[1][2] = 4.75461652596774;
   fWeightMatrix0to1[2][2] = 7.38069498368426;
   fWeightMatrix0to1[3][2] = -1.97039411863167;
   fWeightMatrix0to1[4][2] = 9.58334367959913;
   fWeightMatrix0to1[5][2] = 1.49581498047536;
   fWeightMatrix0to1[6][2] = -13.839334338775;
   fWeightMatrix0to1[7][2] = 3.50038582505494;
   fWeightMatrix0to1[8][2] = -8.0514589046293;
   fWeightMatrix0to1[9][2] = 1.96821035261809;
   fWeightMatrix0to1[10][2] = 1.28284940130731;
   fWeightMatrix0to1[11][2] = 1.69844243434869;
   fWeightMatrix0to1[12][2] = 1.69721061403965;
   fWeightMatrix0to1[13][2] = 1.25531056284023;
   fWeightMatrix0to1[14][2] = -0.891671641218978;
   fWeightMatrix0to1[0][3] = 0.28380931527147;
   fWeightMatrix0to1[1][3] = 0.90221331013342;
   fWeightMatrix0to1[2][3] = -1.55216166559908;
   fWeightMatrix0to1[3][3] = 1.48129709759862;
   fWeightMatrix0to1[4][3] = 2.85234317006343;
   fWeightMatrix0to1[5][3] = 3.02999350219877;
   fWeightMatrix0to1[6][3] = 0.696777555469621;
   fWeightMatrix0to1[7][3] = -3.85831079634121;
   fWeightMatrix0to1[8][3] = 1.13478360297211;
   fWeightMatrix0to1[9][3] = -0.956936857876437;
   fWeightMatrix0to1[10][3] = -0.169103813608149;
   fWeightMatrix0to1[11][3] = -0.724754893794928;
   fWeightMatrix0to1[12][3] = -1.31022394892557;
   fWeightMatrix0to1[13][3] = 1.30583166075323;
   fWeightMatrix0to1[14][3] = 1.0903318486337;
   fWeightMatrix0to1[0][4] = -0.0372705365181824;
   fWeightMatrix0to1[1][4] = 0.757682936777651;
   fWeightMatrix0to1[2][4] = -0.687133358463534;
   fWeightMatrix0to1[3][4] = 1.9246370195199;
   fWeightMatrix0to1[4][4] = -1.73069642660455;
   fWeightMatrix0to1[5][4] = -1.96660649388139;
   fWeightMatrix0to1[6][4] = 2.20627629256709;
   fWeightMatrix0to1[7][4] = -4.23055905835439;
   fWeightMatrix0to1[8][4] = 3.22253587420322;
   fWeightMatrix0to1[9][4] = 0.139022313567004;
   fWeightMatrix0to1[10][4] = 0.206544239952216;
   fWeightMatrix0to1[11][4] = -0.261702214379056;
   fWeightMatrix0to1[12][4] = 1.72162079836972;
   fWeightMatrix0to1[13][4] = 0.978048840024222;
   fWeightMatrix0to1[14][4] = 1.79192653049458;
   fWeightMatrix0to1[0][5] = -1.881053113709;
   fWeightMatrix0to1[1][5] = -1.88373346845124;
   fWeightMatrix0to1[2][5] = -0.14974380812912;
   fWeightMatrix0to1[3][5] = -1.14834332679788;
   fWeightMatrix0to1[4][5] = 7.33594051325204;
   fWeightMatrix0to1[5][5] = 3.95032185772805;
   fWeightMatrix0to1[6][5] = -8.62675015637463;
   fWeightMatrix0to1[7][5] = 1.09070953585509;
   fWeightMatrix0to1[8][5] = -5.954029791446;
   fWeightMatrix0to1[9][5] = -2.16492496507817;
   fWeightMatrix0to1[10][5] = -1.75351257821889;
   fWeightMatrix0to1[11][5] = -0.630526990536636;
   fWeightMatrix0to1[12][5] = -1.90749412547793;
   fWeightMatrix0to1[13][5] = -1.83588127649827;
   fWeightMatrix0to1[14][5] = -1.76071635888049;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.961016975967;
   fWeightMatrix1to2[0][1] = -3.21857236860917;
   fWeightMatrix1to2[0][2] = 1.53463558900415;
   fWeightMatrix1to2[0][3] = 2.26362759347748;
   fWeightMatrix1to2[0][4] = -1.54336625679245;
   fWeightMatrix1to2[0][5] = 2.15750293590983;
   fWeightMatrix1to2[0][6] = -1.32302180549043;
   fWeightMatrix1to2[0][7] = -2.14498757150173;
   fWeightMatrix1to2[0][8] = -1.36258474619701;
   fWeightMatrix1to2[0][9] = -0.529629480437216;
   fWeightMatrix1to2[0][10] = -0.81626529913621;
   fWeightMatrix1to2[0][11] = -1.60714881478244;
   fWeightMatrix1to2[0][12] = 0.257421273806864;
   fWeightMatrix1to2[0][13] = 0.567126625452961;
   fWeightMatrix1to2[0][14] = -1.22590498287244;
   fWeightMatrix1to2[0][15] = 2.5976815041874;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 251;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 226;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 187;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 226;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 3;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 4;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 4;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 6;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 8;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 8;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
