// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sun May 10 05:47:26 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 2000000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+20" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,255]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,48]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,64]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[26][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][26];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 26; fWeights[1] = new double[26]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.28587963260234;
   fWeightMatrix0to1[1][0] = 6.45923123679583;
   fWeightMatrix0to1[2][0] = 8.31702711975938;
   fWeightMatrix0to1[3][0] = 9.00871949970102;
   fWeightMatrix0to1[4][0] = -1.97973296257032;
   fWeightMatrix0to1[5][0] = -4.01156943174533;
   fWeightMatrix0to1[6][0] = -7.6133193633701;
   fWeightMatrix0to1[7][0] = -4.03094097689489;
   fWeightMatrix0to1[8][0] = 1.48555931244004;
   fWeightMatrix0to1[9][0] = -2.08628425438505;
   fWeightMatrix0to1[10][0] = 0.336373806959283;
   fWeightMatrix0to1[11][0] = 1.69634782496649;
   fWeightMatrix0to1[12][0] = -12.1700599112106;
   fWeightMatrix0to1[13][0] = 0.0829877625263613;
   fWeightMatrix0to1[14][0] = -3.9738732396478;
   fWeightMatrix0to1[15][0] = -4.52932063112896;
   fWeightMatrix0to1[16][0] = -0.939799902469315;
   fWeightMatrix0to1[17][0] = -2.26394409193973;
   fWeightMatrix0to1[18][0] = -5.2849452698292;
   fWeightMatrix0to1[19][0] = 17.4877306331101;
   fWeightMatrix0to1[20][0] = 1.12291869967981;
   fWeightMatrix0to1[21][0] = -0.313547669460399;
   fWeightMatrix0to1[22][0] = 4.70853378093372;
   fWeightMatrix0to1[23][0] = -16.0666355680535;
   fWeightMatrix0to1[24][0] = -13.4194232832381;
   fWeightMatrix0to1[0][1] = -24.8589811418677;
   fWeightMatrix0to1[1][1] = -18.2415351982183;
   fWeightMatrix0to1[2][1] = -7.34447924514649;
   fWeightMatrix0to1[3][1] = -19.881576193465;
   fWeightMatrix0to1[4][1] = 16.2281992169056;
   fWeightMatrix0to1[5][1] = 3.88718107604607;
   fWeightMatrix0to1[6][1] = 16.3844763790547;
   fWeightMatrix0to1[7][1] = 25.4824466637436;
   fWeightMatrix0to1[8][1] = -12.4548560502352;
   fWeightMatrix0to1[9][1] = 0.891077090469469;
   fWeightMatrix0to1[10][1] = -11.5166562871094;
   fWeightMatrix0to1[11][1] = -21.7962824112286;
   fWeightMatrix0to1[12][1] = 12.3234931262435;
   fWeightMatrix0to1[13][1] = -0.892033897779198;
   fWeightMatrix0to1[14][1] = 0.805583086178534;
   fWeightMatrix0to1[15][1] = 17.5290389353826;
   fWeightMatrix0to1[16][1] = 1.47609394686432;
   fWeightMatrix0to1[17][1] = 4.04896845060021;
   fWeightMatrix0to1[18][1] = -0.829232087206368;
   fWeightMatrix0to1[19][1] = -16.117928629539;
   fWeightMatrix0to1[20][1] = 10.3029849109813;
   fWeightMatrix0to1[21][1] = -0.190248765200242;
   fWeightMatrix0to1[22][1] = -6.2138821260517;
   fWeightMatrix0to1[23][1] = 20.2363860919283;
   fWeightMatrix0to1[24][1] = 3.13314365292402;
   fWeightMatrix0to1[0][2] = 29.215913319941;
   fWeightMatrix0to1[1][2] = 22.5634492269109;
   fWeightMatrix0to1[2][2] = 2.44328364571671;
   fWeightMatrix0to1[3][2] = 3.00610551657112;
   fWeightMatrix0to1[4][2] = -27.138780746316;
   fWeightMatrix0to1[5][2] = -3.5893154884492;
   fWeightMatrix0to1[6][2] = -13.0473485952498;
   fWeightMatrix0to1[7][2] = -19.4085698552676;
   fWeightMatrix0to1[8][2] = 7.98007443604584;
   fWeightMatrix0to1[9][2] = 2.31313172360238;
   fWeightMatrix0to1[10][2] = 4.58466142207932;
   fWeightMatrix0to1[11][2] = 17.947612226756;
   fWeightMatrix0to1[12][2] = 3.56447848356742;
   fWeightMatrix0to1[13][2] = 0.910540397511274;
   fWeightMatrix0to1[14][2] = 7.21027716182481;
   fWeightMatrix0to1[15][2] = -7.55141412559761;
   fWeightMatrix0to1[16][2] = 1.50063200099129;
   fWeightMatrix0to1[17][2] = 1.61625104341924;
   fWeightMatrix0to1[18][2] = 5.9430573277049;
   fWeightMatrix0to1[19][2] = -11.418239551827;
   fWeightMatrix0to1[20][2] = -17.7905618603324;
   fWeightMatrix0to1[21][2] = -0.777504350915433;
   fWeightMatrix0to1[22][2] = 9.15903476694711;
   fWeightMatrix0to1[23][2] = 1.27743058466668;
   fWeightMatrix0to1[24][2] = 8.29103241985097;
   fWeightMatrix0to1[0][3] = -0.188573197306645;
   fWeightMatrix0to1[1][3] = -0.555705638537016;
   fWeightMatrix0to1[2][3] = 0.588882646022225;
   fWeightMatrix0to1[3][3] = 5.67721338828174;
   fWeightMatrix0to1[4][3] = -4.28898510625559;
   fWeightMatrix0to1[5][3] = 1.93537452392061;
   fWeightMatrix0to1[6][3] = 7.16886051287872;
   fWeightMatrix0to1[7][3] = 3.03428902410094;
   fWeightMatrix0to1[8][3] = -1.4809939626651;
   fWeightMatrix0to1[9][3] = 0.552137740673942;
   fWeightMatrix0to1[10][3] = -2.70798782064331;
   fWeightMatrix0to1[11][3] = 1.68364678095673;
   fWeightMatrix0to1[12][3] = -1.72860063894537;
   fWeightMatrix0to1[13][3] = 0.00484517000096205;
   fWeightMatrix0to1[14][3] = 0.228078194036091;
   fWeightMatrix0to1[15][3] = 1.46998063528916;
   fWeightMatrix0to1[16][3] = 0.627733259695895;
   fWeightMatrix0to1[17][3] = 2.46698197193734;
   fWeightMatrix0to1[18][3] = -2.25432886999711;
   fWeightMatrix0to1[19][3] = 5.44861649742668;
   fWeightMatrix0to1[20][3] = 4.32321402380055;
   fWeightMatrix0to1[21][3] = 0.989535925349604;
   fWeightMatrix0to1[22][3] = -0.11955996011749;
   fWeightMatrix0to1[23][3] = -0.552473779710864;
   fWeightMatrix0to1[24][3] = -2.59090615873636;
   fWeightMatrix0to1[0][4] = -1.1173910681944;
   fWeightMatrix0to1[1][4] = 0.607552279084414;
   fWeightMatrix0to1[2][4] = 3.57449621560965;
   fWeightMatrix0to1[3][4] = 0.428109889354012;
   fWeightMatrix0to1[4][4] = 2.65645909263675;
   fWeightMatrix0to1[5][4] = -0.653417619891696;
   fWeightMatrix0to1[6][4] = -3.85765252406518;
   fWeightMatrix0to1[7][4] = 0.171852274780592;
   fWeightMatrix0to1[8][4] = 0.0216155004253115;
   fWeightMatrix0to1[9][4] = 1.95597157721316;
   fWeightMatrix0to1[10][4] = 4.84126316184505;
   fWeightMatrix0to1[11][4] = 0.306819016801607;
   fWeightMatrix0to1[12][4] = -1.61551723722486;
   fWeightMatrix0to1[13][4] = 2.42277787379009;
   fWeightMatrix0to1[14][4] = 0.974432232892924;
   fWeightMatrix0to1[15][4] = 2.25829055263868;
   fWeightMatrix0to1[16][4] = 1.33373049584739;
   fWeightMatrix0to1[17][4] = -0.26399654298794;
   fWeightMatrix0to1[18][4] = 1.81734676530838;
   fWeightMatrix0to1[19][4] = 5.30957575093427;
   fWeightMatrix0to1[20][4] = 3.97205877344321;
   fWeightMatrix0to1[21][4] = 2.31083939778921;
   fWeightMatrix0to1[22][4] = 1.40528481128566;
   fWeightMatrix0to1[23][4] = -0.295087843261257;
   fWeightMatrix0to1[24][4] = 3.61143055825316;
   fWeightMatrix0to1[0][5] = 1.6655628747656;
   fWeightMatrix0to1[1][5] = -1.7469109022081;
   fWeightMatrix0to1[2][5] = -2.21938296806593;
   fWeightMatrix0to1[3][5] = -1.68813373526288;
   fWeightMatrix0to1[4][5] = -16.4137443649648;
   fWeightMatrix0to1[5][5] = 0.176064623641534;
   fWeightMatrix0to1[6][5] = -0.604057968966888;
   fWeightMatrix0to1[7][5] = -2.12864192074416;
   fWeightMatrix0to1[8][5] = -2.15497984423915;
   fWeightMatrix0to1[9][5] = -2.30894878660545;
   fWeightMatrix0to1[10][5] = -4.29785446371574;
   fWeightMatrix0to1[11][5] = 2.34103256759496;
   fWeightMatrix0to1[12][5] = 1.00655692269019;
   fWeightMatrix0to1[13][5] = -2.10492328642018;
   fWeightMatrix0to1[14][5] = -2.26534084975629;
   fWeightMatrix0to1[15][5] = 1.37062384172627;
   fWeightMatrix0to1[16][5] = -0.650358688340948;
   fWeightMatrix0to1[17][5] = -1.76206753289801;
   fWeightMatrix0to1[18][5] = -0.909760701882934;
   fWeightMatrix0to1[19][5] = -7.80747564854799;
   fWeightMatrix0to1[20][5] = -2.85546484951713;
   fWeightMatrix0to1[21][5] = -2.18261529535307;
   fWeightMatrix0to1[22][5] = -1.72695065025504;
   fWeightMatrix0to1[23][5] = 3.3753855499189;
   fWeightMatrix0to1[24][5] = -0.754970387564418;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.841231887113876;
   fWeightMatrix1to2[0][1] = 0.974726590703537;
   fWeightMatrix1to2[0][2] = 0.632075057600167;
   fWeightMatrix1to2[0][3] = -1.11684842365244;
   fWeightMatrix1to2[0][4] = 1.62687256200231;
   fWeightMatrix1to2[0][5] = 0.901692215443922;
   fWeightMatrix1to2[0][6] = -0.855092305625139;
   fWeightMatrix1to2[0][7] = -0.877758371815141;
   fWeightMatrix1to2[0][8] = -1.6896476183124;
   fWeightMatrix1to2[0][9] = -0.527255204763618;
   fWeightMatrix1to2[0][10] = 1.38913732716926;
   fWeightMatrix1to2[0][11] = 1.89394008623278;
   fWeightMatrix1to2[0][12] = -1.34602226225021;
   fWeightMatrix1to2[0][13] = -0.390845324233708;
   fWeightMatrix1to2[0][14] = -2.32717269439366;
   fWeightMatrix1to2[0][15] = 0.984489777341282;
   fWeightMatrix1to2[0][16] = 1.24871371787977;
   fWeightMatrix1to2[0][17] = 3.79585107640298;
   fWeightMatrix1to2[0][18] = -1.324670386839;
   fWeightMatrix1to2[0][19] = 0.661291417250711;
   fWeightMatrix1to2[0][20] = -1.82610739126163;
   fWeightMatrix1to2[0][21] = 0.311010997061078;
   fWeightMatrix1to2[0][22] = -1.63958315470248;
   fWeightMatrix1to2[0][23] = 0.968414520312885;
   fWeightMatrix1to2[0][24] = 0.843675559004815;
   fWeightMatrix1to2[0][25] = 0.823096015764172;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 255;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 255;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 255;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 31;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 48;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 48;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 59;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 64;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 64;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
