// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sun May 10 01:55:02 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+20" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,255]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,23]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,28]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[26][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][26];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 26; fWeights[1] = new double[26]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.808958935824193;
   fWeightMatrix0to1[1][0] = -3.05116035429518;
   fWeightMatrix0to1[2][0] = 4.75507969837357;
   fWeightMatrix0to1[3][0] = 6.62317094237471;
   fWeightMatrix0to1[4][0] = -10.4930856548893;
   fWeightMatrix0to1[5][0] = -1.91133017286231;
   fWeightMatrix0to1[6][0] = -8.77164756446058;
   fWeightMatrix0to1[7][0] = 4.14986489629065;
   fWeightMatrix0to1[8][0] = -5.42781183265026;
   fWeightMatrix0to1[9][0] = -0.650183534365268;
   fWeightMatrix0to1[10][0] = -6.79595446877424;
   fWeightMatrix0to1[11][0] = -2.77962578116962;
   fWeightMatrix0to1[12][0] = -1.55546869272747;
   fWeightMatrix0to1[13][0] = 3.67914761394058;
   fWeightMatrix0to1[14][0] = -4.22489914304322;
   fWeightMatrix0to1[15][0] = -0.374154252093324;
   fWeightMatrix0to1[16][0] = -1.10864628519485;
   fWeightMatrix0to1[17][0] = -1.45646229977256;
   fWeightMatrix0to1[18][0] = 0.0652285963968287;
   fWeightMatrix0to1[19][0] = 1.18972347683724;
   fWeightMatrix0to1[20][0] = 6.10748386671372;
   fWeightMatrix0to1[21][0] = -0.722793785509148;
   fWeightMatrix0to1[22][0] = -0.144476280626234;
   fWeightMatrix0to1[23][0] = -2.09729503197782;
   fWeightMatrix0to1[24][0] = -3.50185997135178;
   fWeightMatrix0to1[0][1] = -0.957496963426778;
   fWeightMatrix0to1[1][1] = 13.8846299356676;
   fWeightMatrix0to1[2][1] = -4.63150439995762;
   fWeightMatrix0to1[3][1] = -9.40444739513654;
   fWeightMatrix0to1[4][1] = 1.76738867018058;
   fWeightMatrix0to1[5][1] = 0.31935854949233;
   fWeightMatrix0to1[6][1] = 10.2572124314266;
   fWeightMatrix0to1[7][1] = 2.45144781605035;
   fWeightMatrix0to1[8][1] = 2.07912909549511;
   fWeightMatrix0to1[9][1] = 0.0114910720919029;
   fWeightMatrix0to1[10][1] = -0.804135741535398;
   fWeightMatrix0to1[11][1] = -3.30689410772959;
   fWeightMatrix0to1[12][1] = 2.47388131582353;
   fWeightMatrix0to1[13][1] = -9.6829592331507;
   fWeightMatrix0to1[14][1] = 2.62971617746404;
   fWeightMatrix0to1[15][1] = 7.8156658763778;
   fWeightMatrix0to1[16][1] = 1.56217145488213;
   fWeightMatrix0to1[17][1] = 14.3398955902732;
   fWeightMatrix0to1[18][1] = 4.43021544460326;
   fWeightMatrix0to1[19][1] = -0.517678252825626;
   fWeightMatrix0to1[20][1] = -23.7728278883052;
   fWeightMatrix0to1[21][1] = 2.13398805582844;
   fWeightMatrix0to1[22][1] = -0.249523596931966;
   fWeightMatrix0to1[23][1] = -0.665615597352801;
   fWeightMatrix0to1[24][1] = -4.45872910361455;
   fWeightMatrix0to1[0][2] = 2.46604204006446;
   fWeightMatrix0to1[1][2] = 7.43911745708634;
   fWeightMatrix0to1[2][2] = -10.0644611174071;
   fWeightMatrix0to1[3][2] = -2.67281214385458;
   fWeightMatrix0to1[4][2] = -2.06646232433628;
   fWeightMatrix0to1[5][2] = -1.51640560144519;
   fWeightMatrix0to1[6][2] = -4.37971510018403;
   fWeightMatrix0to1[7][2] = -1.02572830893571;
   fWeightMatrix0to1[8][2] = 5.24979669237808;
   fWeightMatrix0to1[9][2] = 2.06742972314492;
   fWeightMatrix0to1[10][2] = 0.835798185974656;
   fWeightMatrix0to1[11][2] = -1.92811469986177;
   fWeightMatrix0to1[12][2] = -0.221137073151113;
   fWeightMatrix0to1[13][2] = 1.86913410745007;
   fWeightMatrix0to1[14][2] = 6.57255510539987;
   fWeightMatrix0to1[15][2] = -2.79384301717913;
   fWeightMatrix0to1[16][2] = 0.778775693964975;
   fWeightMatrix0to1[17][2] = -13.7177335073159;
   fWeightMatrix0to1[18][2] = 0.0175002415577795;
   fWeightMatrix0to1[19][2] = 0.00896451234646833;
   fWeightMatrix0to1[20][2] = 14.8807441203424;
   fWeightMatrix0to1[21][2] = -0.531336534249465;
   fWeightMatrix0to1[22][2] = 1.12577305928509;
   fWeightMatrix0to1[23][2] = 7.03699978187805;
   fWeightMatrix0to1[24][2] = 19.6683926196903;
   fWeightMatrix0to1[0][3] = 1.30821175038314;
   fWeightMatrix0to1[1][3] = -3.18554073904137;
   fWeightMatrix0to1[2][3] = 1.26826748120994;
   fWeightMatrix0to1[3][3] = 3.21103474055866;
   fWeightMatrix0to1[4][3] = -0.224082791524741;
   fWeightMatrix0to1[5][3] = 2.79598696775559;
   fWeightMatrix0to1[6][3] = 0.288743650706969;
   fWeightMatrix0to1[7][3] = 3.40216530483439;
   fWeightMatrix0to1[8][3] = -1.33649493918011;
   fWeightMatrix0to1[9][3] = 0.096435569093287;
   fWeightMatrix0to1[10][3] = 5.40855521297004;
   fWeightMatrix0to1[11][3] = 5.50436848141401;
   fWeightMatrix0to1[12][3] = -0.480323092222545;
   fWeightMatrix0to1[13][3] = 1.35006376687326;
   fWeightMatrix0to1[14][3] = -0.49471975004923;
   fWeightMatrix0to1[15][3] = 1.4914112988673;
   fWeightMatrix0to1[16][3] = 0.517743611195762;
   fWeightMatrix0to1[17][3] = 2.85049238817353;
   fWeightMatrix0to1[18][3] = 0.439462666465312;
   fWeightMatrix0to1[19][3] = 0.686561736153442;
   fWeightMatrix0to1[20][3] = -0.383997523333361;
   fWeightMatrix0to1[21][3] = 0.144050430868685;
   fWeightMatrix0to1[22][3] = 0.00967109587075542;
   fWeightMatrix0to1[23][3] = -1.60846098817104;
   fWeightMatrix0to1[24][3] = -2.65620428388161;
   fWeightMatrix0to1[0][4] = -0.111438901690596;
   fWeightMatrix0to1[1][4] = -2.45392621246261;
   fWeightMatrix0to1[2][4] = 2.32716064184351;
   fWeightMatrix0to1[3][4] = 3.14933036992132;
   fWeightMatrix0to1[4][4] = -1.85393509380686;
   fWeightMatrix0to1[5][4] = 2.21010045354463;
   fWeightMatrix0to1[6][4] = -2.40015434926052;
   fWeightMatrix0to1[7][4] = 1.92928261862363;
   fWeightMatrix0to1[8][4] = -0.12085898839757;
   fWeightMatrix0to1[9][4] = 1.46917309032159;
   fWeightMatrix0to1[10][4] = 2.15874980210983;
   fWeightMatrix0to1[11][4] = 4.6469511922666;
   fWeightMatrix0to1[12][4] = 0.871644162510613;
   fWeightMatrix0to1[13][4] = 1.69692687066268;
   fWeightMatrix0to1[14][4] = -0.334989104333151;
   fWeightMatrix0to1[15][4] = 2.7250217121182;
   fWeightMatrix0to1[16][4] = 0.876268183427875;
   fWeightMatrix0to1[17][4] = -1.33543444057921;
   fWeightMatrix0to1[18][4] = 2.70077487572978;
   fWeightMatrix0to1[19][4] = 0.546240962905185;
   fWeightMatrix0to1[20][4] = -0.610744200858836;
   fWeightMatrix0to1[21][4] = 1.38919616928755;
   fWeightMatrix0to1[22][4] = 1.22677779554295;
   fWeightMatrix0to1[23][4] = 2.35342527725778;
   fWeightMatrix0to1[24][4] = -0.107689212266185;
   fWeightMatrix0to1[0][5] = -1.82652396727495;
   fWeightMatrix0to1[1][5] = 7.61957023865807;
   fWeightMatrix0to1[2][5] = -10.04433527466;
   fWeightMatrix0to1[3][5] = -4.40177233918435;
   fWeightMatrix0to1[4][5] = 2.17197733400934;
   fWeightMatrix0to1[5][5] = -0.367128543295251;
   fWeightMatrix0to1[6][5] = -0.826824782933066;
   fWeightMatrix0to1[7][5] = -1.84609540702802;
   fWeightMatrix0to1[8][5] = -2.56960161903891;
   fWeightMatrix0to1[9][5] = -1.04054979820723;
   fWeightMatrix0to1[10][5] = 1.40451410855299;
   fWeightMatrix0to1[11][5] = 0.488971590550242;
   fWeightMatrix0to1[12][5] = -2.72548368325744;
   fWeightMatrix0to1[13][5] = -2.76633651579377;
   fWeightMatrix0to1[14][5] = 0.274068761404359;
   fWeightMatrix0to1[15][5] = -0.853997437654897;
   fWeightMatrix0to1[16][5] = -0.798371666752644;
   fWeightMatrix0to1[17][5] = -0.798145671696479;
   fWeightMatrix0to1[18][5] = -2.48709961333796;
   fWeightMatrix0to1[19][5] = -3.00717979105724;
   fWeightMatrix0to1[20][5] = 0.675201595999721;
   fWeightMatrix0to1[21][5] = -0.176570652926438;
   fWeightMatrix0to1[22][5] = -2.31851475929904;
   fWeightMatrix0to1[23][5] = -0.378057942215041;
   fWeightMatrix0to1[24][5] = 1.40180054978062;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.022447123454577;
   fWeightMatrix1to2[0][1] = 1.08806330257273;
   fWeightMatrix1to2[0][2] = 4.02756730261393;
   fWeightMatrix1to2[0][3] = -5.45411820557101;
   fWeightMatrix1to2[0][4] = -0.688936714688017;
   fWeightMatrix1to2[0][5] = -1.30032212866266;
   fWeightMatrix1to2[0][6] = 1.23910441073157;
   fWeightMatrix1to2[0][7] = 2.18300747122479;
   fWeightMatrix1to2[0][8] = -2.02954681671205;
   fWeightMatrix1to2[0][9] = 0.758591048158111;
   fWeightMatrix1to2[0][10] = 1.66938014564496;
   fWeightMatrix1to2[0][11] = -2.07447403293242;
   fWeightMatrix1to2[0][12] = 0.720053758473857;
   fWeightMatrix1to2[0][13] = 5.00941160627581;
   fWeightMatrix1to2[0][14] = -1.40968298242522;
   fWeightMatrix1to2[0][15] = -2.56670676127091;
   fWeightMatrix1to2[0][16] = 0.932953662583429;
   fWeightMatrix1to2[0][17] = 1.7711920994051;
   fWeightMatrix1to2[0][18] = -1.16381687723303;
   fWeightMatrix1to2[0][19] = 0.0512438514425148;
   fWeightMatrix1to2[0][20] = 1.42670585282514;
   fWeightMatrix1to2[0][21] = 1.87073335569087;
   fWeightMatrix1to2[0][22] = -0.00376499658774022;
   fWeightMatrix1to2[0][23] = 3.08254839343755;
   fWeightMatrix1to2[0][24] = 1.11493864796525;
   fWeightMatrix1to2[0][25] = -3.19095810303564;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 255;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 252;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 255;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 23;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 11;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 23;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 28;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 12;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 28;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
