// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sun May 10 00:46:58 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+20" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,255]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,34]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,41]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[26][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][26];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 26; fWeights[1] = new double[26]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -3.05651571386801;
   fWeightMatrix0to1[1][0] = 6.62494501636578;
   fWeightMatrix0to1[2][0] = 8.28005865499278;
   fWeightMatrix0to1[3][0] = 2.23968112876874;
   fWeightMatrix0to1[4][0] = -4.66128750505469;
   fWeightMatrix0to1[5][0] = -1.61890479263411;
   fWeightMatrix0to1[6][0] = 1.34546923723829;
   fWeightMatrix0to1[7][0] = 1.41247206543656;
   fWeightMatrix0to1[8][0] = -7.07739460554545;
   fWeightMatrix0to1[9][0] = -1.28560317161585;
   fWeightMatrix0to1[10][0] = -7.51793534620338;
   fWeightMatrix0to1[11][0] = 5.75640593201383;
   fWeightMatrix0to1[12][0] = -6.71361861160033;
   fWeightMatrix0to1[13][0] = 0.764246427965949;
   fWeightMatrix0to1[14][0] = -3.90421775869889;
   fWeightMatrix0to1[15][0] = -3.43789168365395;
   fWeightMatrix0to1[16][0] = -1.05674436765707;
   fWeightMatrix0to1[17][0] = 9.18301135759795;
   fWeightMatrix0to1[18][0] = -0.0420146722328485;
   fWeightMatrix0to1[19][0] = 0.78887716927885;
   fWeightMatrix0to1[20][0] = -1.06736831939371;
   fWeightMatrix0to1[21][0] = -9.08714564221233;
   fWeightMatrix0to1[22][0] = 6.58446735054977;
   fWeightMatrix0to1[23][0] = -4.96890172631334;
   fWeightMatrix0to1[24][0] = -0.888402322491231;
   fWeightMatrix0to1[0][1] = -0.924734405815076;
   fWeightMatrix0to1[1][1] = 1.44741516233244;
   fWeightMatrix0to1[2][1] = -22.9554958384679;
   fWeightMatrix0to1[3][1] = -1.54013674442443;
   fWeightMatrix0to1[4][1] = 2.26187458007607;
   fWeightMatrix0to1[5][1] = 0.239818990802943;
   fWeightMatrix0to1[6][1] = 4.81993894820025;
   fWeightMatrix0to1[7][1] = -1.0313305600631;
   fWeightMatrix0to1[8][1] = 4.83455570238269;
   fWeightMatrix0to1[9][1] = 0.641452058500889;
   fWeightMatrix0to1[10][1] = 9.10867364272259;
   fWeightMatrix0to1[11][1] = -10.1281706370417;
   fWeightMatrix0to1[12][1] = 13.2223553012744;
   fWeightMatrix0to1[13][1] = -1.41988392879677;
   fWeightMatrix0to1[14][1] = 5.15881930048839;
   fWeightMatrix0to1[15][1] = 5.25437119896569;
   fWeightMatrix0to1[16][1] = 1.72086179052538;
   fWeightMatrix0to1[17][1] = 7.49691856684187;
   fWeightMatrix0to1[18][1] = 0.434100605873751;
   fWeightMatrix0to1[19][1] = -0.0619381073901228;
   fWeightMatrix0to1[20][1] = -3.23337121973171;
   fWeightMatrix0to1[21][1] = -6.15051949722037;
   fWeightMatrix0to1[22][1] = -1.36386795962032;
   fWeightMatrix0to1[23][1] = 18.4643399841781;
   fWeightMatrix0to1[24][1] = 4.43590215921503;
   fWeightMatrix0to1[0][2] = 2.37192165627346;
   fWeightMatrix0to1[1][2] = -2.0817819519642;
   fWeightMatrix0to1[2][2] = 1.98752696362994;
   fWeightMatrix0to1[3][2] = 1.50437497791396;
   fWeightMatrix0to1[4][2] = -1.93904720407672;
   fWeightMatrix0to1[5][2] = -1.12350126035755;
   fWeightMatrix0to1[6][2] = -0.571999598587323;
   fWeightMatrix0to1[7][2] = -0.882634110126878;
   fWeightMatrix0to1[8][2] = 1.38150659457809;
   fWeightMatrix0to1[9][2] = -0.366904977390682;
   fWeightMatrix0to1[10][2] = -8.62314572108884;
   fWeightMatrix0to1[11][2] = 6.10133736387012;
   fWeightMatrix0to1[12][2] = -7.71728865645636;
   fWeightMatrix0to1[13][2] = 2.22367648922557;
   fWeightMatrix0to1[14][2] = 5.85934379786046;
   fWeightMatrix0to1[15][2] = 2.87749826033774;
   fWeightMatrix0to1[16][2] = 0.563122144537383;
   fWeightMatrix0to1[17][2] = -3.82874641319067;
   fWeightMatrix0to1[18][2] = 4.68323769487446;
   fWeightMatrix0to1[19][2] = -0.048878627837951;
   fWeightMatrix0to1[20][2] = -2.15601678957253;
   fWeightMatrix0to1[21][2] = 2.49630024432716;
   fWeightMatrix0to1[22][2] = 9.61327315481163;
   fWeightMatrix0to1[23][2] = -10.446503636675;
   fWeightMatrix0to1[24][2] = 2.60113845329007;
   fWeightMatrix0to1[0][3] = 1.11123201795402;
   fWeightMatrix0to1[1][3] = -0.894894836138196;
   fWeightMatrix0to1[2][3] = 1.39189976773789;
   fWeightMatrix0to1[3][3] = 0.839825495787561;
   fWeightMatrix0to1[4][3] = 2.57275735395077;
   fWeightMatrix0to1[5][3] = 2.5649238720255;
   fWeightMatrix0to1[6][3] = 0.418010433933302;
   fWeightMatrix0to1[7][3] = 3.08220133520537;
   fWeightMatrix0to1[8][3] = -0.136429684959538;
   fWeightMatrix0to1[9][3] = 0.428653917628808;
   fWeightMatrix0to1[10][3] = 0.807771061578459;
   fWeightMatrix0to1[11][3] = 4.15545614308136;
   fWeightMatrix0to1[12][3] = -0.757607370728958;
   fWeightMatrix0to1[13][3] = 0.265836210716064;
   fWeightMatrix0to1[14][3] = 0.193316446031981;
   fWeightMatrix0to1[15][3] = 1.12571729919974;
   fWeightMatrix0to1[16][3] = 0.964644069225785;
   fWeightMatrix0to1[17][3] = 3.99491682807359;
   fWeightMatrix0to1[18][3] = -0.457381813940956;
   fWeightMatrix0to1[19][3] = 0.685807555114336;
   fWeightMatrix0to1[20][3] = 4.30389700654669;
   fWeightMatrix0to1[21][3] = 2.01526020548374;
   fWeightMatrix0to1[22][3] = 1.0091752070555;
   fWeightMatrix0to1[23][3] = -0.144994888921947;
   fWeightMatrix0to1[24][3] = 0.679985289314218;
   fWeightMatrix0to1[0][4] = -0.350018965449451;
   fWeightMatrix0to1[1][4] = -0.663362167181879;
   fWeightMatrix0to1[2][4] = 1.84471259887528;
   fWeightMatrix0to1[3][4] = 1.50920764422986;
   fWeightMatrix0to1[4][4] = 0.625487838784336;
   fWeightMatrix0to1[5][4] = 2.45093270610312;
   fWeightMatrix0to1[6][4] = -1.03067226185575;
   fWeightMatrix0to1[7][4] = 1.18207603866471;
   fWeightMatrix0to1[8][4] = -1.25085737049388;
   fWeightMatrix0to1[9][4] = 2.20064357227956;
   fWeightMatrix0to1[10][4] = -1.51991930328274;
   fWeightMatrix0to1[11][4] = 0.87360863633454;
   fWeightMatrix0to1[12][4] = 0.134270366474084;
   fWeightMatrix0to1[13][4] = 1.95917516897489;
   fWeightMatrix0to1[14][4] = 3.24389581957038;
   fWeightMatrix0to1[15][4] = 2.98194435731495;
   fWeightMatrix0to1[16][4] = 1.62703008814171;
   fWeightMatrix0to1[17][4] = 1.33380549787218;
   fWeightMatrix0to1[18][4] = 2.1154355442431;
   fWeightMatrix0to1[19][4] = 0.363594095119776;
   fWeightMatrix0to1[20][4] = 0.272312332757565;
   fWeightMatrix0to1[21][4] = 6.66860464399885;
   fWeightMatrix0to1[22][4] = 2.54343779945327;
   fWeightMatrix0to1[23][4] = 2.02814525733001;
   fWeightMatrix0to1[24][4] = 1.30760386541601;
   fWeightMatrix0to1[0][5] = -1.15414951504046;
   fWeightMatrix0to1[1][5] = -1.77820132615453;
   fWeightMatrix0to1[2][5] = -6.50474141415368;
   fWeightMatrix0to1[3][5] = -1.62664808177821;
   fWeightMatrix0to1[4][5] = -2.00607471979725;
   fWeightMatrix0to1[5][5] = -0.364789814123654;
   fWeightMatrix0to1[6][5] = -1.76954432181251;
   fWeightMatrix0to1[7][5] = -1.42699325564685;
   fWeightMatrix0to1[8][5] = -2.21742026401684;
   fWeightMatrix0to1[9][5] = -2.19936912146472;
   fWeightMatrix0to1[10][5] = 0.670872322311737;
   fWeightMatrix0to1[11][5] = 0.614139650062733;
   fWeightMatrix0to1[12][5] = -0.922416486570876;
   fWeightMatrix0to1[13][5] = -1.53123175319133;
   fWeightMatrix0to1[14][5] = 10.7134541805198;
   fWeightMatrix0to1[15][5] = 0.839818150465942;
   fWeightMatrix0to1[16][5] = -1.06871758455;
   fWeightMatrix0to1[17][5] = -4.14193378258729;
   fWeightMatrix0to1[18][5] = -1.56575322983912;
   fWeightMatrix0to1[19][5] = -2.97916839471985;
   fWeightMatrix0to1[20][5] = -0.525177453993377;
   fWeightMatrix0to1[21][5] = -3.19471393707441;
   fWeightMatrix0to1[22][5] = -3.32126139426025;
   fWeightMatrix0to1[23][5] = 1.02486365955243;
   fWeightMatrix0to1[24][5] = -1.09055569550274;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.38005589532282;
   fWeightMatrix1to2[0][1] = 0.396669819629849;
   fWeightMatrix1to2[0][2] = 1.22220533891208;
   fWeightMatrix1to2[0][3] = -0.917257838600176;
   fWeightMatrix1to2[0][4] = 2.21294208962447;
   fWeightMatrix1to2[0][5] = -1.20141165159143;
   fWeightMatrix1to2[0][6] = -0.936955945820648;
   fWeightMatrix1to2[0][7] = 0.13439028852167;
   fWeightMatrix1to2[0][8] = 1.92195941756034;
   fWeightMatrix1to2[0][9] = -0.0563895949141922;
   fWeightMatrix1to2[0][10] = 1.30007014149739;
   fWeightMatrix1to2[0][11] = 1.94587160591085;
   fWeightMatrix1to2[0][12] = -1.6958627488074;
   fWeightMatrix1to2[0][13] = -0.0179495726012417;
   fWeightMatrix1to2[0][14] = 2.50705087029648;
   fWeightMatrix1to2[0][15] = -2.76730261319843;
   fWeightMatrix1to2[0][16] = -0.820724631436174;
   fWeightMatrix1to2[0][17] = 0.910612424813497;
   fWeightMatrix1to2[0][18] = 1.99637327362115;
   fWeightMatrix1to2[0][19] = -0.246009488874614;
   fWeightMatrix1to2[0][20] = 0.848760620306545;
   fWeightMatrix1to2[0][21] = -1.30680915532636;
   fWeightMatrix1to2[0][22] = -1.72436692462983;
   fWeightMatrix1to2[0][23] = 1.18405825493497;
   fWeightMatrix1to2[0][24] = 2.48533369805903;
   fWeightMatrix1to2[0][25] = -2.79605534045852;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 250;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 255;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 255;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 10;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 34;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 34;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 12;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 41;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 41;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
