// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sun May 10 10:04:22 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 99147
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "10" [Number of training cycles]
HiddenLayers: "N+100" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,226]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,4]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,8]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[106][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][106];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 106; fWeights[1] = new double[106]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.63095919838372;
   fWeightMatrix0to1[1][0] = 1.99116608090776;
   fWeightMatrix0to1[2][0] = 1.78343854483268;
   fWeightMatrix0to1[3][0] = 1.17419322184971;
   fWeightMatrix0to1[4][0] = -2.9594312875832;
   fWeightMatrix0to1[5][0] = -1.40641508906122;
   fWeightMatrix0to1[6][0] = -0.892788301453855;
   fWeightMatrix0to1[7][0] = 1.80710481495201;
   fWeightMatrix0to1[8][0] = -3.7857167480703;
   fWeightMatrix0to1[9][0] = -3.53895716877211;
   fWeightMatrix0to1[10][0] = -1.57146088792234;
   fWeightMatrix0to1[11][0] = -0.457099687211786;
   fWeightMatrix0to1[12][0] = -1.2514328965634;
   fWeightMatrix0to1[13][0] = -0.534740210883621;
   fWeightMatrix0to1[14][0] = -0.613037825269454;
   fWeightMatrix0to1[15][0] = 1.05868648083401;
   fWeightMatrix0to1[16][0] = -0.757500345903848;
   fWeightMatrix0to1[17][0] = 1.58578777910368;
   fWeightMatrix0to1[18][0] = -0.101922272301997;
   fWeightMatrix0to1[19][0] = 0.991700588804342;
   fWeightMatrix0to1[20][0] = -0.472780747520442;
   fWeightMatrix0to1[21][0] = -0.735275080497543;
   fWeightMatrix0to1[22][0] = 0.2295558291275;
   fWeightMatrix0to1[23][0] = -0.207725062388498;
   fWeightMatrix0to1[24][0] = -1.23683596850816;
   fWeightMatrix0to1[25][0] = -0.34437769512519;
   fWeightMatrix0to1[26][0] = 1.36095586824821;
   fWeightMatrix0to1[27][0] = -1.17270930832618;
   fWeightMatrix0to1[28][0] = -3.34917410925381;
   fWeightMatrix0to1[29][0] = -0.000573937972469155;
   fWeightMatrix0to1[30][0] = 3.45161221153196;
   fWeightMatrix0to1[31][0] = 3.26777798514142;
   fWeightMatrix0to1[32][0] = -0.3789903713356;
   fWeightMatrix0to1[33][0] = -0.160016923082724;
   fWeightMatrix0to1[34][0] = 0.976302168973849;
   fWeightMatrix0to1[35][0] = -0.383771044626518;
   fWeightMatrix0to1[36][0] = -1.45499201734476;
   fWeightMatrix0to1[37][0] = 2.06368361648576;
   fWeightMatrix0to1[38][0] = -1.081721295452;
   fWeightMatrix0to1[39][0] = 0.924868311731682;
   fWeightMatrix0to1[40][0] = 1.39313755069195;
   fWeightMatrix0to1[41][0] = 0.766348698128303;
   fWeightMatrix0to1[42][0] = 1.57810723416214;
   fWeightMatrix0to1[43][0] = 1.00640466745821;
   fWeightMatrix0to1[44][0] = -0.638766888213194;
   fWeightMatrix0to1[45][0] = -1.61260107155519;
   fWeightMatrix0to1[46][0] = 0.743571594820966;
   fWeightMatrix0to1[47][0] = 0.0381314018045105;
   fWeightMatrix0to1[48][0] = 1.25620117918827;
   fWeightMatrix0to1[49][0] = 2.54756056501631;
   fWeightMatrix0to1[50][0] = 1.96267788003409;
   fWeightMatrix0to1[51][0] = 0.983136079300999;
   fWeightMatrix0to1[52][0] = -1.50602362186343;
   fWeightMatrix0to1[53][0] = 1.93401529411628;
   fWeightMatrix0to1[54][0] = -1.42838066872794;
   fWeightMatrix0to1[55][0] = -1.03290296894056;
   fWeightMatrix0to1[56][0] = -0.932908323965219;
   fWeightMatrix0to1[57][0] = -1.79666218796911;
   fWeightMatrix0to1[58][0] = 1.11555809702993;
   fWeightMatrix0to1[59][0] = 0.471108879606098;
   fWeightMatrix0to1[60][0] = -1.4480527279501;
   fWeightMatrix0to1[61][0] = 0.23863897770747;
   fWeightMatrix0to1[62][0] = -0.30297242147114;
   fWeightMatrix0to1[63][0] = 0.665410233240362;
   fWeightMatrix0to1[64][0] = 1.49785163033033;
   fWeightMatrix0to1[65][0] = -0.451302960462593;
   fWeightMatrix0to1[66][0] = 0.142856138479;
   fWeightMatrix0to1[67][0] = -1.46542399548907;
   fWeightMatrix0to1[68][0] = -0.336916054319021;
   fWeightMatrix0to1[69][0] = -0.766418314023733;
   fWeightMatrix0to1[70][0] = -0.661179782331105;
   fWeightMatrix0to1[71][0] = -3.04816749371424;
   fWeightMatrix0to1[72][0] = 0.454789321402452;
   fWeightMatrix0to1[73][0] = 1.16292943045965;
   fWeightMatrix0to1[74][0] = 1.93393672811701;
   fWeightMatrix0to1[75][0] = -0.553463560199782;
   fWeightMatrix0to1[76][0] = -1.84443067730658;
   fWeightMatrix0to1[77][0] = -1.69811382639004;
   fWeightMatrix0to1[78][0] = 1.4604887567002;
   fWeightMatrix0to1[79][0] = 0.592628579695956;
   fWeightMatrix0to1[80][0] = 1.59378372003853;
   fWeightMatrix0to1[81][0] = 0.924159515864609;
   fWeightMatrix0to1[82][0] = 2.28967328107945;
   fWeightMatrix0to1[83][0] = -0.805424326253297;
   fWeightMatrix0to1[84][0] = -0.926782067655765;
   fWeightMatrix0to1[85][0] = -0.222299921181504;
   fWeightMatrix0to1[86][0] = 1.30094827824094;
   fWeightMatrix0to1[87][0] = -1.83582692337732;
   fWeightMatrix0to1[88][0] = -1.74119803522957;
   fWeightMatrix0to1[89][0] = -1.59317538644385;
   fWeightMatrix0to1[90][0] = -0.453157475401745;
   fWeightMatrix0to1[91][0] = 0.708754010465689;
   fWeightMatrix0to1[92][0] = 1.1655833366441;
   fWeightMatrix0to1[93][0] = -1.51134995333732;
   fWeightMatrix0to1[94][0] = -0.72355257712993;
   fWeightMatrix0to1[95][0] = 1.31232938361387;
   fWeightMatrix0to1[96][0] = -1.01663451615891;
   fWeightMatrix0to1[97][0] = -1.50275404731471;
   fWeightMatrix0to1[98][0] = -2.23011045266813;
   fWeightMatrix0to1[99][0] = 0.448369119645352;
   fWeightMatrix0to1[100][0] = -1.86487708672462;
   fWeightMatrix0to1[101][0] = -2.33254367834924;
   fWeightMatrix0to1[102][0] = 0.101437779807487;
   fWeightMatrix0to1[103][0] = 3.00399937851375;
   fWeightMatrix0to1[104][0] = -1.15410342732972;
   fWeightMatrix0to1[0][1] = 1.85935103361326;
   fWeightMatrix0to1[1][1] = -1.05039245347929;
   fWeightMatrix0to1[2][1] = -1.48468320065883;
   fWeightMatrix0to1[3][1] = -0.159356688724285;
   fWeightMatrix0to1[4][1] = 0.480464757577237;
   fWeightMatrix0to1[5][1] = -1.35560130008826;
   fWeightMatrix0to1[6][1] = 0.409860972969523;
   fWeightMatrix0to1[7][1] = 0.799005580104632;
   fWeightMatrix0to1[8][1] = 0.915909337909143;
   fWeightMatrix0to1[9][1] = -4.80124480160043;
   fWeightMatrix0to1[10][1] = 1.95520143524994;
   fWeightMatrix0to1[11][1] = 0.39057924734886;
   fWeightMatrix0to1[12][1] = -0.447399930379754;
   fWeightMatrix0to1[13][1] = 1.0172946640829;
   fWeightMatrix0to1[14][1] = -1.03038264139559;
   fWeightMatrix0to1[15][1] = -1.8101771129281;
   fWeightMatrix0to1[16][1] = 0.329791751082498;
   fWeightMatrix0to1[17][1] = 0.00297305990570765;
   fWeightMatrix0to1[18][1] = 2.15329425561536;
   fWeightMatrix0to1[19][1] = 1.06159989346015;
   fWeightMatrix0to1[20][1] = 0.137870692954553;
   fWeightMatrix0to1[21][1] = -0.123783743525929;
   fWeightMatrix0to1[22][1] = 0.123234285023739;
   fWeightMatrix0to1[23][1] = -1.17725167401963;
   fWeightMatrix0to1[24][1] = 1.26713041602546;
   fWeightMatrix0to1[25][1] = 0.59207318408377;
   fWeightMatrix0to1[26][1] = -1.6859479178802;
   fWeightMatrix0to1[27][1] = 0.697969724555903;
   fWeightMatrix0to1[28][1] = -1.3047052021313;
   fWeightMatrix0to1[29][1] = 0.370086953916429;
   fWeightMatrix0to1[30][1] = 0.160344001620479;
   fWeightMatrix0to1[31][1] = 2.82777460517706;
   fWeightMatrix0to1[32][1] = -1.40715034768118;
   fWeightMatrix0to1[33][1] = 0.327156523514507;
   fWeightMatrix0to1[34][1] = 1.09145629182382;
   fWeightMatrix0to1[35][1] = 1.57475344956676;
   fWeightMatrix0to1[36][1] = 0.396190165862697;
   fWeightMatrix0to1[37][1] = -1.04815679695581;
   fWeightMatrix0to1[38][1] = -0.186899171195188;
   fWeightMatrix0to1[39][1] = -1.11612770463678;
   fWeightMatrix0to1[40][1] = 1.61833605651091;
   fWeightMatrix0to1[41][1] = 1.35618043651508;
   fWeightMatrix0to1[42][1] = -0.684357065941602;
   fWeightMatrix0to1[43][1] = -0.419725879023277;
   fWeightMatrix0to1[44][1] = 0.124418789935637;
   fWeightMatrix0to1[45][1] = -0.866927472323943;
   fWeightMatrix0to1[46][1] = 0.693654927690407;
   fWeightMatrix0to1[47][1] = 2.27690110427723;
   fWeightMatrix0to1[48][1] = -0.10832437353583;
   fWeightMatrix0to1[49][1] = -1.17936358843464;
   fWeightMatrix0to1[50][1] = 0.818243859357978;
   fWeightMatrix0to1[51][1] = 1.35572171880724;
   fWeightMatrix0to1[52][1] = 0.622385650695392;
   fWeightMatrix0to1[53][1] = 1.18596264648543;
   fWeightMatrix0to1[54][1] = -0.915357575288944;
   fWeightMatrix0to1[55][1] = 1.98557987149461;
   fWeightMatrix0to1[56][1] = 1.15817968578372;
   fWeightMatrix0to1[57][1] = 0.753579296312485;
   fWeightMatrix0to1[58][1] = 0.271501358417001;
   fWeightMatrix0to1[59][1] = 0.623725945241296;
   fWeightMatrix0to1[60][1] = -0.130322028105921;
   fWeightMatrix0to1[61][1] = -0.245601141568409;
   fWeightMatrix0to1[62][1] = 0.962011593282365;
   fWeightMatrix0to1[63][1] = -0.926496333937074;
   fWeightMatrix0to1[64][1] = -0.407286647285058;
   fWeightMatrix0to1[65][1] = 1.5800354579678;
   fWeightMatrix0to1[66][1] = 1.67614976353071;
   fWeightMatrix0to1[67][1] = 0.111162058176178;
   fWeightMatrix0to1[68][1] = 2.46102296375706;
   fWeightMatrix0to1[69][1] = 1.96298181698982;
   fWeightMatrix0to1[70][1] = -1.63642852167942;
   fWeightMatrix0to1[71][1] = 1.18565126330253;
   fWeightMatrix0to1[72][1] = 0.383312684064027;
   fWeightMatrix0to1[73][1] = 0.488457477867383;
   fWeightMatrix0to1[74][1] = -1.24738993072745;
   fWeightMatrix0to1[75][1] = -0.897065328612452;
   fWeightMatrix0to1[76][1] = 1.36032270183771;
   fWeightMatrix0to1[77][1] = 1.93544937257895;
   fWeightMatrix0to1[78][1] = -1.5025049448957;
   fWeightMatrix0to1[79][1] = 0.102957920399347;
   fWeightMatrix0to1[80][1] = -0.0888406913369319;
   fWeightMatrix0to1[81][1] = 0.395199531733679;
   fWeightMatrix0to1[82][1] = 3.11318575461618;
   fWeightMatrix0to1[83][1] = -0.368548633958667;
   fWeightMatrix0to1[84][1] = -0.176017580537516;
   fWeightMatrix0to1[85][1] = -0.593319582616441;
   fWeightMatrix0to1[86][1] = 1.30149606431463;
   fWeightMatrix0to1[87][1] = 1.86621654209514;
   fWeightMatrix0to1[88][1] = 1.87486137017018;
   fWeightMatrix0to1[89][1] = 0.6081144294729;
   fWeightMatrix0to1[90][1] = -0.161488748119071;
   fWeightMatrix0to1[91][1] = -2.85332784149557;
   fWeightMatrix0to1[92][1] = 1.5794582579514;
   fWeightMatrix0to1[93][1] = 0.731924136121363;
   fWeightMatrix0to1[94][1] = -1.00999978334629;
   fWeightMatrix0to1[95][1] = -0.278673145096169;
   fWeightMatrix0to1[96][1] = 0.797189297777078;
   fWeightMatrix0to1[97][1] = 0.522194588107797;
   fWeightMatrix0to1[98][1] = -1.88982191515841;
   fWeightMatrix0to1[99][1] = 2.91992762335446;
   fWeightMatrix0to1[100][1] = 0.827529906304919;
   fWeightMatrix0to1[101][1] = -1.05069031863304;
   fWeightMatrix0to1[102][1] = 0.179341345357332;
   fWeightMatrix0to1[103][1] = 1.28809901311674;
   fWeightMatrix0to1[104][1] = 1.17787211969529;
   fWeightMatrix0to1[0][2] = 0.979843929462067;
   fWeightMatrix0to1[1][2] = -0.301823314930713;
   fWeightMatrix0to1[2][2] = -3.88620884383591;
   fWeightMatrix0to1[3][2] = -0.652225080863492;
   fWeightMatrix0to1[4][2] = 2.83669996857495;
   fWeightMatrix0to1[5][2] = 1.93139866223474;
   fWeightMatrix0to1[6][2] = 1.31548575141638;
   fWeightMatrix0to1[7][2] = 0.951539885243747;
   fWeightMatrix0to1[8][2] = 3.16994171185628;
   fWeightMatrix0to1[9][2] = -3.59390416127373;
   fWeightMatrix0to1[10][2] = -1.26166661652225;
   fWeightMatrix0to1[11][2] = 0.25409899034312;
   fWeightMatrix0to1[12][2] = -0.776054662512833;
   fWeightMatrix0to1[13][2] = 1.27549406319531;
   fWeightMatrix0to1[14][2] = 1.79167191401448;
   fWeightMatrix0to1[15][2] = -1.99456030416271;
   fWeightMatrix0to1[16][2] = 1.63717508575389;
   fWeightMatrix0to1[17][2] = 0.226410210982445;
   fWeightMatrix0to1[18][2] = -1.0315063268969;
   fWeightMatrix0to1[19][2] = -0.530891513926613;
   fWeightMatrix0to1[20][2] = 1.36147820722729;
   fWeightMatrix0to1[21][2] = 0.556605783055665;
   fWeightMatrix0to1[22][2] = 1.55899716588437;
   fWeightMatrix0to1[23][2] = -0.04405256788077;
   fWeightMatrix0to1[24][2] = 1.96488042181934;
   fWeightMatrix0to1[25][2] = -1.17143025171273;
   fWeightMatrix0to1[26][2] = 1.17414759693063;
   fWeightMatrix0to1[27][2] = 0.410442062331881;
   fWeightMatrix0to1[28][2] = -0.727414760341109;
   fWeightMatrix0to1[29][2] = -0.745976044615883;
   fWeightMatrix0to1[30][2] = -4.70304170184068;
   fWeightMatrix0to1[31][2] = -0.404756553291583;
   fWeightMatrix0to1[32][2] = -1.20691021377785;
   fWeightMatrix0to1[33][2] = -1.30528853854288;
   fWeightMatrix0to1[34][2] = -2.64747478672472;
   fWeightMatrix0to1[35][2] = -0.18719553639292;
   fWeightMatrix0to1[36][2] = -0.835174911884139;
   fWeightMatrix0to1[37][2] = -1.4622293494786;
   fWeightMatrix0to1[38][2] = 1.26033581454798;
   fWeightMatrix0to1[39][2] = -0.374011060224883;
   fWeightMatrix0to1[40][2] = 0.802792757459974;
   fWeightMatrix0to1[41][2] = -0.727986933089989;
   fWeightMatrix0to1[42][2] = -0.00523047440422838;
   fWeightMatrix0to1[43][2] = 2.01596985401152;
   fWeightMatrix0to1[44][2] = 1.16274561104183;
   fWeightMatrix0to1[45][2] = -1.27675952766375;
   fWeightMatrix0to1[46][2] = -1.48777855015363;
   fWeightMatrix0to1[47][2] = -0.243991806829841;
   fWeightMatrix0to1[48][2] = -0.0719346138767823;
   fWeightMatrix0to1[49][2] = -3.25749115218526;
   fWeightMatrix0to1[50][2] = 0.912212113143669;
   fWeightMatrix0to1[51][2] = 0.974562517498922;
   fWeightMatrix0to1[52][2] = 1.53548269785994;
   fWeightMatrix0to1[53][2] = -0.423380696633103;
   fWeightMatrix0to1[54][2] = 0.674603281347392;
   fWeightMatrix0to1[55][2] = -0.31431956845885;
   fWeightMatrix0to1[56][2] = -1.42247695291498;
   fWeightMatrix0to1[57][2] = 1.73856349632543;
   fWeightMatrix0to1[58][2] = 1.26047160588855;
   fWeightMatrix0to1[59][2] = -0.841137823961031;
   fWeightMatrix0to1[60][2] = -0.686646977592218;
   fWeightMatrix0to1[61][2] = 1.35932474091882;
   fWeightMatrix0to1[62][2] = 0.964328313773356;
   fWeightMatrix0to1[63][2] = 0.495990111293285;
   fWeightMatrix0to1[64][2] = -0.0787713212687233;
   fWeightMatrix0to1[65][2] = -0.161337387893227;
   fWeightMatrix0to1[66][2] = 3.20207326135683;
   fWeightMatrix0to1[67][2] = 1.62091338149198;
   fWeightMatrix0to1[68][2] = 3.86970076401997;
   fWeightMatrix0to1[69][2] = -0.342738443400221;
   fWeightMatrix0to1[70][2] = 0.481984410248514;
   fWeightMatrix0to1[71][2] = 0.737738071526306;
   fWeightMatrix0to1[72][2] = -0.897467619015695;
   fWeightMatrix0to1[73][2] = -0.452625967810357;
   fWeightMatrix0to1[74][2] = -1.79568928047853;
   fWeightMatrix0to1[75][2] = -0.426935641021133;
   fWeightMatrix0to1[76][2] = -1.12614761101142;
   fWeightMatrix0to1[77][2] = 1.94296856048254;
   fWeightMatrix0to1[78][2] = -1.96877961811291;
   fWeightMatrix0to1[79][2] = 2.20217770326552;
   fWeightMatrix0to1[80][2] = -0.571432331445045;
   fWeightMatrix0to1[81][2] = 0.975392899924202;
   fWeightMatrix0to1[82][2] = -0.902139621484851;
   fWeightMatrix0to1[83][2] = 0.45905510610919;
   fWeightMatrix0to1[84][2] = 1.40141183165416;
   fWeightMatrix0to1[85][2] = -1.18508255078642;
   fWeightMatrix0to1[86][2] = 0.210512678506426;
   fWeightMatrix0to1[87][2] = 2.48189982591542;
   fWeightMatrix0to1[88][2] = -1.27423311405947;
   fWeightMatrix0to1[89][2] = -1.12862437243802;
   fWeightMatrix0to1[90][2] = -0.65013391795405;
   fWeightMatrix0to1[91][2] = -2.57107685855139;
   fWeightMatrix0to1[92][2] = 2.16677532035052;
   fWeightMatrix0to1[93][2] = -0.0967770972129695;
   fWeightMatrix0to1[94][2] = 0.569004554602176;
   fWeightMatrix0to1[95][2] = -0.132798104135072;
   fWeightMatrix0to1[96][2] = -0.375644783758593;
   fWeightMatrix0to1[97][2] = -1.10070112800201;
   fWeightMatrix0to1[98][2] = 0.104190514586661;
   fWeightMatrix0to1[99][2] = -0.833029758434315;
   fWeightMatrix0to1[100][2] = 0.883299591838698;
   fWeightMatrix0to1[101][2] = -1.15251701112938;
   fWeightMatrix0to1[102][2] = -0.7663235593902;
   fWeightMatrix0to1[103][2] = 3.64873968467751;
   fWeightMatrix0to1[104][2] = 0.442294103744891;
   fWeightMatrix0to1[0][3] = 0.236399028955802;
   fWeightMatrix0to1[1][3] = 2.24830536901607;
   fWeightMatrix0to1[2][3] = -1.2252208375653;
   fWeightMatrix0to1[3][3] = 1.26140635773307;
   fWeightMatrix0to1[4][3] = 0.533630670280337;
   fWeightMatrix0to1[5][3] = -0.376229720533609;
   fWeightMatrix0to1[6][3] = -0.299787178878297;
   fWeightMatrix0to1[7][3] = 1.06694676727437;
   fWeightMatrix0to1[8][3] = -1.04410800469819;
   fWeightMatrix0to1[9][3] = 1.01623879166892;
   fWeightMatrix0to1[10][3] = 1.99030281255983;
   fWeightMatrix0to1[11][3] = 1.77023178520641;
   fWeightMatrix0to1[12][3] = 2.3178436222958;
   fWeightMatrix0to1[13][3] = -0.86642541680095;
   fWeightMatrix0to1[14][3] = 1.09925859827557;
   fWeightMatrix0to1[15][3] = -1.45025053790337;
   fWeightMatrix0to1[16][3] = 0.985143301986126;
   fWeightMatrix0to1[17][3] = -0.811742433339388;
   fWeightMatrix0to1[18][3] = -0.882037504274626;
   fWeightMatrix0to1[19][3] = 0.831010423581173;
   fWeightMatrix0to1[20][3] = 1.74739759514192;
   fWeightMatrix0to1[21][3] = 1.09646234777598;
   fWeightMatrix0to1[22][3] = 1.30156524191143;
   fWeightMatrix0to1[23][3] = 1.38630293181354;
   fWeightMatrix0to1[24][3] = 0.277478008547098;
   fWeightMatrix0to1[25][3] = 0.0355391116864716;
   fWeightMatrix0to1[26][3] = 0.603474798395975;
   fWeightMatrix0to1[27][3] = 1.93941431160753;
   fWeightMatrix0to1[28][3] = -0.639370660957357;
   fWeightMatrix0to1[29][3] = 1.07151595005191;
   fWeightMatrix0to1[30][3] = -1.38150993825731;
   fWeightMatrix0to1[31][3] = -0.839107994793207;
   fWeightMatrix0to1[32][3] = 0.710567524922111;
   fWeightMatrix0to1[33][3] = 0.671027296096782;
   fWeightMatrix0to1[34][3] = -0.966930385505224;
   fWeightMatrix0to1[35][3] = 1.19097234028618;
   fWeightMatrix0to1[36][3] = 2.11624166335696;
   fWeightMatrix0to1[37][3] = 1.2931562594615;
   fWeightMatrix0to1[38][3] = 0.284626956566108;
   fWeightMatrix0to1[39][3] = -0.194701286831657;
   fWeightMatrix0to1[40][3] = -1.52522443467633;
   fWeightMatrix0to1[41][3] = -1.05241330854914;
   fWeightMatrix0to1[42][3] = 1.1231208105765;
   fWeightMatrix0to1[43][3] = -0.167165763308736;
   fWeightMatrix0to1[44][3] = -0.977472054687102;
   fWeightMatrix0to1[45][3] = 0.851577555692158;
   fWeightMatrix0to1[46][3] = -0.709069487992628;
   fWeightMatrix0to1[47][3] = -0.251134677902301;
   fWeightMatrix0to1[48][3] = -0.497289783899514;
   fWeightMatrix0to1[49][3] = 1.49051951810925;
   fWeightMatrix0to1[50][3] = -0.789566978917288;
   fWeightMatrix0to1[51][3] = -0.739020731259446;
   fWeightMatrix0to1[52][3] = -0.0558476456526678;
   fWeightMatrix0to1[53][3] = -0.471550394017869;
   fWeightMatrix0to1[54][3] = -1.07724746043271;
   fWeightMatrix0to1[55][3] = 1.832236161385;
   fWeightMatrix0to1[56][3] = -0.591279347221743;
   fWeightMatrix0to1[57][3] = -0.344554289084711;
   fWeightMatrix0to1[58][3] = 1.79584127154599;
   fWeightMatrix0to1[59][3] = 1.05891394565465;
   fWeightMatrix0to1[60][3] = 0.845235353399616;
   fWeightMatrix0to1[61][3] = 0.833480347330899;
   fWeightMatrix0to1[62][3] = 1.44174152237034;
   fWeightMatrix0to1[63][3] = 1.79730296012758;
   fWeightMatrix0to1[64][3] = 1.19556462000243;
   fWeightMatrix0to1[65][3] = -0.767155715757505;
   fWeightMatrix0to1[66][3] = -0.0687843512548119;
   fWeightMatrix0to1[67][3] = -0.88203287856767;
   fWeightMatrix0to1[68][3] = 1.24278516148425;
   fWeightMatrix0to1[69][3] = 0.942026163379441;
   fWeightMatrix0to1[70][3] = 0.673152932859157;
   fWeightMatrix0to1[71][3] = 1.85202726567779;
   fWeightMatrix0to1[72][3] = 1.60874709200578;
   fWeightMatrix0to1[73][3] = 1.97626066856051;
   fWeightMatrix0to1[74][3] = -0.213094003677159;
   fWeightMatrix0to1[75][3] = 2.98974564348475;
   fWeightMatrix0to1[76][3] = 1.36817874301222;
   fWeightMatrix0to1[77][3] = -1.28972217141621;
   fWeightMatrix0to1[78][3] = -0.0260777876641089;
   fWeightMatrix0to1[79][3] = -0.55715321898122;
   fWeightMatrix0to1[80][3] = 1.93362326064746;
   fWeightMatrix0to1[81][3] = 0.533882952903283;
   fWeightMatrix0to1[82][3] = 1.18383443025335;
   fWeightMatrix0to1[83][3] = 1.80178831239623;
   fWeightMatrix0to1[84][3] = 0.200428127652882;
   fWeightMatrix0to1[85][3] = 2.55285445982194;
   fWeightMatrix0to1[86][3] = 2.0690910683978;
   fWeightMatrix0to1[87][3] = 0.464442188104317;
   fWeightMatrix0to1[88][3] = -0.193801044612347;
   fWeightMatrix0to1[89][3] = 2.12516926957122;
   fWeightMatrix0to1[90][3] = -0.836077780285884;
   fWeightMatrix0to1[91][3] = 0.519311367361845;
   fWeightMatrix0to1[92][3] = 2.30249566054941;
   fWeightMatrix0to1[93][3] = 0.0452992937707613;
   fWeightMatrix0to1[94][3] = -0.173936019032477;
   fWeightMatrix0to1[95][3] = 1.09478169891968;
   fWeightMatrix0to1[96][3] = -0.254005897304035;
   fWeightMatrix0to1[97][3] = 1.2840081652414;
   fWeightMatrix0to1[98][3] = -1.0031856949075;
   fWeightMatrix0to1[99][3] = 0.717777355057405;
   fWeightMatrix0to1[100][3] = -0.105774298379816;
   fWeightMatrix0to1[101][3] = 2.36099847864297;
   fWeightMatrix0to1[102][3] = 1.72767662452254;
   fWeightMatrix0to1[103][3] = 1.14306374810907;
   fWeightMatrix0to1[104][3] = -0.286873521057707;
   fWeightMatrix0to1[0][4] = 0.571014995698458;
   fWeightMatrix0to1[1][4] = 1.09474920523839;
   fWeightMatrix0to1[2][4] = 2.52272528598191;
   fWeightMatrix0to1[3][4] = -2.28384228077413;
   fWeightMatrix0to1[4][4] = -1.42247484343942;
   fWeightMatrix0to1[5][4] = 0.23196951422726;
   fWeightMatrix0to1[6][4] = -0.64790964890203;
   fWeightMatrix0to1[7][4] = -0.359504453581619;
   fWeightMatrix0to1[8][4] = -1.77394620808831;
   fWeightMatrix0to1[9][4] = 2.70994864551685;
   fWeightMatrix0to1[10][4] = 0.122451054787514;
   fWeightMatrix0to1[11][4] = -1.13414050716086;
   fWeightMatrix0to1[12][4] = -1.00985616811257;
   fWeightMatrix0to1[13][4] = 0.492488271834459;
   fWeightMatrix0to1[14][4] = 1.70695334953158;
   fWeightMatrix0to1[15][4] = 2.96200408939706;
   fWeightMatrix0to1[16][4] = 1.43595181259098;
   fWeightMatrix0to1[17][4] = 0.466863588520389;
   fWeightMatrix0to1[18][4] = -0.675786979138839;
   fWeightMatrix0to1[19][4] = 0.915286727536934;
   fWeightMatrix0to1[20][4] = -0.641505323600088;
   fWeightMatrix0to1[21][4] = -0.591208205687237;
   fWeightMatrix0to1[22][4] = -0.226327922101387;
   fWeightMatrix0to1[23][4] = 1.38164450648032;
   fWeightMatrix0to1[24][4] = -0.958164927491724;
   fWeightMatrix0to1[25][4] = 2.41699391702605;
   fWeightMatrix0to1[26][4] = 1.87670390156614;
   fWeightMatrix0to1[27][4] = 0.398642486850339;
   fWeightMatrix0to1[28][4] = 0.379145171612745;
   fWeightMatrix0to1[29][4] = 0.114811695909748;
   fWeightMatrix0to1[30][4] = 1.99611213338358;
   fWeightMatrix0to1[31][4] = -1.31538387386878;
   fWeightMatrix0to1[32][4] = 1.1015064585082;
   fWeightMatrix0to1[33][4] = 2.5113391057297;
   fWeightMatrix0to1[34][4] = 1.65433424673565;
   fWeightMatrix0to1[35][4] = -0.868365130839889;
   fWeightMatrix0to1[36][4] = 1.94658065320779;
   fWeightMatrix0to1[37][4] = -0.602034385271582;
   fWeightMatrix0to1[38][4] = 2.10527284599733;
   fWeightMatrix0to1[39][4] = 2.72686121985258;
   fWeightMatrix0to1[40][4] = -0.2356289683421;
   fWeightMatrix0to1[41][4] = 0.643612460992222;
   fWeightMatrix0to1[42][4] = 0.321187724152294;
   fWeightMatrix0to1[43][4] = -0.1258823146327;
   fWeightMatrix0to1[44][4] = 1.87280304589202;
   fWeightMatrix0to1[45][4] = 0.509763100590211;
   fWeightMatrix0to1[46][4] = 0.584845528700961;
   fWeightMatrix0to1[47][4] = -0.243957116959126;
   fWeightMatrix0to1[48][4] = 1.40609820608389;
   fWeightMatrix0to1[49][4] = 2.91950486192691;
   fWeightMatrix0to1[50][4] = 1.1778014656165;
   fWeightMatrix0to1[51][4] = 0.519149092424371;
   fWeightMatrix0to1[52][4] = -1.4896631304598;
   fWeightMatrix0to1[53][4] = 2.32116703249839;
   fWeightMatrix0to1[54][4] = 0.910375934163755;
   fWeightMatrix0to1[55][4] = -0.557015965412498;
   fWeightMatrix0to1[56][4] = 0.8463974800851;
   fWeightMatrix0to1[57][4] = 0.23205459181147;
   fWeightMatrix0to1[58][4] = 1.37306210860693;
   fWeightMatrix0to1[59][4] = 2.02074221861424;
   fWeightMatrix0to1[60][4] = -0.125163433922254;
   fWeightMatrix0to1[61][4] = -0.268128754101989;
   fWeightMatrix0to1[62][4] = 1.72250458314439;
   fWeightMatrix0to1[63][4] = 1.35785988564543;
   fWeightMatrix0to1[64][4] = 1.18039812656865;
   fWeightMatrix0to1[65][4] = 0.421230940521923;
   fWeightMatrix0to1[66][4] = -0.70721961836844;
   fWeightMatrix0to1[67][4] = -0.191337864493005;
   fWeightMatrix0to1[68][4] = 1.16159860289461;
   fWeightMatrix0to1[69][4] = 0.294867297459377;
   fWeightMatrix0to1[70][4] = 1.10916228276694;
   fWeightMatrix0to1[71][4] = -0.774497068242272;
   fWeightMatrix0to1[72][4] = -1.14140990651114;
   fWeightMatrix0to1[73][4] = -1.27380539150748;
   fWeightMatrix0to1[74][4] = 1.0072115433339;
   fWeightMatrix0to1[75][4] = -0.387784649489706;
   fWeightMatrix0to1[76][4] = 1.58694174423302;
   fWeightMatrix0to1[77][4] = 0.649138264735959;
   fWeightMatrix0to1[78][4] = 1.92538271458272;
   fWeightMatrix0to1[79][4] = 1.06698988728565;
   fWeightMatrix0to1[80][4] = -0.688652290852655;
   fWeightMatrix0to1[81][4] = 1.79484509498528;
   fWeightMatrix0to1[82][4] = 1.92419125377868;
   fWeightMatrix0to1[83][4] = 1.15036241321169;
   fWeightMatrix0to1[84][4] = 0.306464780290033;
   fWeightMatrix0to1[85][4] = -0.0441103378312687;
   fWeightMatrix0to1[86][4] = 2.44057590032073;
   fWeightMatrix0to1[87][4] = -0.994410337779119;
   fWeightMatrix0to1[88][4] = 1.37602820719734;
   fWeightMatrix0to1[89][4] = -0.784396449007089;
   fWeightMatrix0to1[90][4] = 2.83109202940763;
   fWeightMatrix0to1[91][4] = -0.57320204414039;
   fWeightMatrix0to1[92][4] = 0.874488102710306;
   fWeightMatrix0to1[93][4] = 0.353328515136079;
   fWeightMatrix0to1[94][4] = 1.39986785549511;
   fWeightMatrix0to1[95][4] = 0.897994835168746;
   fWeightMatrix0to1[96][4] = 0.525514358289534;
   fWeightMatrix0to1[97][4] = 1.92411591386419;
   fWeightMatrix0to1[98][4] = 1.42559784716179;
   fWeightMatrix0to1[99][4] = 1.17365503614385;
   fWeightMatrix0to1[100][4] = 1.18816031901949;
   fWeightMatrix0to1[101][4] = -0.894298590039159;
   fWeightMatrix0to1[102][4] = 2.08183612695216;
   fWeightMatrix0to1[103][4] = -1.85119668867916;
   fWeightMatrix0to1[104][4] = 1.33509500417604;
   fWeightMatrix0to1[0][5] = 0.0670907489170227;
   fWeightMatrix0to1[1][5] = 0.0464647393708292;
   fWeightMatrix0to1[2][5] = 0.202072937846647;
   fWeightMatrix0to1[3][5] = 1.87458779975149;
   fWeightMatrix0to1[4][5] = -1.57125355168501;
   fWeightMatrix0to1[5][5] = -1.61468943302289;
   fWeightMatrix0to1[6][5] = -1.92884878786904;
   fWeightMatrix0to1[7][5] = -0.788498043062582;
   fWeightMatrix0to1[8][5] = 0.637509736790125;
   fWeightMatrix0to1[9][5] = -2.67951839120715;
   fWeightMatrix0to1[10][5] = -0.725955724274371;
   fWeightMatrix0to1[11][5] = -1.39277232853868;
   fWeightMatrix0to1[12][5] = -2.03566175488295;
   fWeightMatrix0to1[13][5] = -1.05507013329285;
   fWeightMatrix0to1[14][5] = -1.86754595840461;
   fWeightMatrix0to1[15][5] = -1.84246254735756;
   fWeightMatrix0to1[16][5] = 0.0156545210498302;
   fWeightMatrix0to1[17][5] = -1.99303386260152;
   fWeightMatrix0to1[18][5] = -2.88106058849467;
   fWeightMatrix0to1[19][5] = -0.631254446279031;
   fWeightMatrix0to1[20][5] = -0.476851977979263;
   fWeightMatrix0to1[21][5] = -1.37069960180815;
   fWeightMatrix0to1[22][5] = -1.66284551686821;
   fWeightMatrix0to1[23][5] = 0.453250171773978;
   fWeightMatrix0to1[24][5] = -0.879328109864915;
   fWeightMatrix0to1[25][5] = -0.249860115311094;
   fWeightMatrix0to1[26][5] = 0.0217393696363603;
   fWeightMatrix0to1[27][5] = -1.26559593357362;
   fWeightMatrix0to1[28][5] = -2.01251431498396;
   fWeightMatrix0to1[29][5] = -1.38328471459139;
   fWeightMatrix0to1[30][5] = -3.34011155464716;
   fWeightMatrix0to1[31][5] = -0.0243480862333474;
   fWeightMatrix0to1[32][5] = -1.93526902031937;
   fWeightMatrix0to1[33][5] = 0.123967072223529;
   fWeightMatrix0to1[34][5] = -2.5204279514586;
   fWeightMatrix0to1[35][5] = 1.02426070105208;
   fWeightMatrix0to1[36][5] = 1.11728018241841;
   fWeightMatrix0to1[37][5] = 0.446272377792267;
   fWeightMatrix0to1[38][5] = 0.523087992972652;
   fWeightMatrix0to1[39][5] = -0.2840740125313;
   fWeightMatrix0to1[40][5] = -0.239450480782479;
   fWeightMatrix0to1[41][5] = -2.05656165520624;
   fWeightMatrix0to1[42][5] = -2.10082313462981;
   fWeightMatrix0to1[43][5] = -1.53421802747922;
   fWeightMatrix0to1[44][5] = -1.34270782429743;
   fWeightMatrix0to1[45][5] = 1.15155862467948;
   fWeightMatrix0to1[46][5] = -1.54467847609095;
   fWeightMatrix0to1[47][5] = -1.3252794200507;
   fWeightMatrix0to1[48][5] = -0.159662553865861;
   fWeightMatrix0to1[49][5] = -0.4804321776339;
   fWeightMatrix0to1[50][5] = -2.08039782283437;
   fWeightMatrix0to1[51][5] = -1.0941528599563;
   fWeightMatrix0to1[52][5] = -2.23441801948465;
   fWeightMatrix0to1[53][5] = 0.120571135099434;
   fWeightMatrix0to1[54][5] = -2.40503522800433;
   fWeightMatrix0to1[55][5] = -0.683151913859562;
   fWeightMatrix0to1[56][5] = -1.61454281419716;
   fWeightMatrix0to1[57][5] = -0.33353434161388;
   fWeightMatrix0to1[58][5] = -2.04146994432939;
   fWeightMatrix0to1[59][5] = -0.505787640912183;
   fWeightMatrix0to1[60][5] = -2.36203305115454;
   fWeightMatrix0to1[61][5] = -1.00510461930098;
   fWeightMatrix0to1[62][5] = 1.00587809616722;
   fWeightMatrix0to1[63][5] = -0.796987501830843;
   fWeightMatrix0to1[64][5] = -0.418351909874508;
   fWeightMatrix0to1[65][5] = -2.00745744073667;
   fWeightMatrix0to1[66][5] = 0.690771892822118;
   fWeightMatrix0to1[67][5] = -1.60703874874067;
   fWeightMatrix0to1[68][5] = 1.46833543686951;
   fWeightMatrix0to1[69][5] = -1.64853078135859;
   fWeightMatrix0to1[70][5] = -1.64532065709203;
   fWeightMatrix0to1[71][5] = 1.23734299383397;
   fWeightMatrix0to1[72][5] = -2.47645354259566;
   fWeightMatrix0to1[73][5] = -2.02646088495834;
   fWeightMatrix0to1[74][5] = -2.79290973683173;
   fWeightMatrix0to1[75][5] = -0.431457265044515;
   fWeightMatrix0to1[76][5] = 0.491661017584581;
   fWeightMatrix0to1[77][5] = 0.24400448774763;
   fWeightMatrix0to1[78][5] = -2.04478007081918;
   fWeightMatrix0to1[79][5] = -0.000803445903776101;
   fWeightMatrix0to1[80][5] = -0.741781352579909;
   fWeightMatrix0to1[81][5] = -0.0855805790837652;
   fWeightMatrix0to1[82][5] = -1.31468419150965;
   fWeightMatrix0to1[83][5] = -1.37174407398386;
   fWeightMatrix0to1[84][5] = -0.809816312652989;
   fWeightMatrix0to1[85][5] = -1.15903458507491;
   fWeightMatrix0to1[86][5] = 0.915886743450734;
   fWeightMatrix0to1[87][5] = -1.02613979044013;
   fWeightMatrix0to1[88][5] = -1.19724981738002;
   fWeightMatrix0to1[89][5] = -1.77379460573885;
   fWeightMatrix0to1[90][5] = -0.169438797205048;
   fWeightMatrix0to1[91][5] = -0.700847157237898;
   fWeightMatrix0to1[92][5] = 0.862230564634117;
   fWeightMatrix0to1[93][5] = -1.5251080047402;
   fWeightMatrix0to1[94][5] = -2.18588650736781;
   fWeightMatrix0to1[95][5] = 0.00671927899928799;
   fWeightMatrix0to1[96][5] = -1.36635440373003;
   fWeightMatrix0to1[97][5] = 0.413449645325817;
   fWeightMatrix0to1[98][5] = -1.42371509174958;
   fWeightMatrix0to1[99][5] = -1.33552791742323;
   fWeightMatrix0to1[100][5] = -1.29922123995342;
   fWeightMatrix0to1[101][5] = -2.64864530973418;
   fWeightMatrix0to1[102][5] = -0.798192311015181;
   fWeightMatrix0to1[103][5] = -1.07547441114177;
   fWeightMatrix0to1[104][5] = -0.428583948509281;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0847321220287262;
   fWeightMatrix1to2[0][1] = -0.283868127853472;
   fWeightMatrix1to2[0][2] = 1.65610107428346;
   fWeightMatrix1to2[0][3] = -2.21128980427388;
   fWeightMatrix1to2[0][4] = -1.85088392980968;
   fWeightMatrix1to2[0][5] = -0.204624754346265;
   fWeightMatrix1to2[0][6] = -0.338324919016793;
   fWeightMatrix1to2[0][7] = -0.0294198317511649;
   fWeightMatrix1to2[0][8] = 1.25503893783979;
   fWeightMatrix1to2[0][9] = -2.46391911488714;
   fWeightMatrix1to2[0][10] = 0.399184432026604;
   fWeightMatrix1to2[0][11] = 0.0304050038274668;
   fWeightMatrix1to2[0][12] = 0.174282385643674;
   fWeightMatrix1to2[0][13] = 0.0741258139445383;
   fWeightMatrix1to2[0][14] = -1.10298716607258;
   fWeightMatrix1to2[0][15] = -0.587075972495373;
   fWeightMatrix1to2[0][16] = -1.59954771461241;
   fWeightMatrix1to2[0][17] = 0.00212722562139325;
   fWeightMatrix1to2[0][18] = -0.0629404600726318;
   fWeightMatrix1to2[0][19] = 0.0641772006532414;
   fWeightMatrix1to2[0][20] = -0.00321371177936051;
   fWeightMatrix1to2[0][21] = -0.108727620749044;
   fWeightMatrix1to2[0][22] = -1.11652172495296;
   fWeightMatrix1to2[0][23] = -0.175666022712777;
   fWeightMatrix1to2[0][24] = -0.142151008329107;
   fWeightMatrix1to2[0][25] = 0.0799796435509021;
   fWeightMatrix1to2[0][26] = 0.250464262432197;
   fWeightMatrix1to2[0][27] = -1.2353970946387;
   fWeightMatrix1to2[0][28] = 0.859633697633614;
   fWeightMatrix1to2[0][29] = -0.0369412638566838;
   fWeightMatrix1to2[0][30] = -2.14819081955856;
   fWeightMatrix1to2[0][31] = 0.451127344449412;
   fWeightMatrix1to2[0][32] = 0.0842089169408645;
   fWeightMatrix1to2[0][33] = -0.225647771714213;
   fWeightMatrix1to2[0][34] = -0.970055728522176;
   fWeightMatrix1to2[0][35] = -0.660534747546637;
   fWeightMatrix1to2[0][36] = 0.413791529662357;
   fWeightMatrix1to2[0][37] = 1.04848907737861;
   fWeightMatrix1to2[0][38] = 0.122462633200422;
   fWeightMatrix1to2[0][39] = -0.0310067778088387;
   fWeightMatrix1to2[0][40] = -0.843944594484301;
   fWeightMatrix1to2[0][41] = -0.237976908322713;
   fWeightMatrix1to2[0][42] = -0.350485369602019;
   fWeightMatrix1to2[0][43] = 0.206509612241828;
   fWeightMatrix1to2[0][44] = 1.21801437641979;
   fWeightMatrix1to2[0][45] = -0.879147190460969;
   fWeightMatrix1to2[0][46] = 0.238342547924771;
   fWeightMatrix1to2[0][47] = -0.198157459201097;
   fWeightMatrix1to2[0][48] = -0.0761669472901925;
   fWeightMatrix1to2[0][49] = -1.60212501535028;
   fWeightMatrix1to2[0][50] = 1.51217650558688;
   fWeightMatrix1to2[0][51] = 0.0507291903180724;
   fWeightMatrix1to2[0][52] = 0.00284292131204514;
   fWeightMatrix1to2[0][53] = -0.349764279680052;
   fWeightMatrix1to2[0][54] = 0.288864008130395;
   fWeightMatrix1to2[0][55] = 0.676482301516283;
   fWeightMatrix1to2[0][56] = 0.172251691601035;
   fWeightMatrix1to2[0][57] = -0.119173133901469;
   fWeightMatrix1to2[0][58] = -1.43515018406908;
   fWeightMatrix1to2[0][59] = -0.986881021681106;
   fWeightMatrix1to2[0][60] = 0.35155404625102;
   fWeightMatrix1to2[0][61] = 0.191617150610383;
   fWeightMatrix1to2[0][62] = 0.103944136166717;
   fWeightMatrix1to2[0][63] = 0.890095444395257;
   fWeightMatrix1to2[0][64] = -0.0538773126713246;
   fWeightMatrix1to2[0][65] = 0.0404137853228387;
   fWeightMatrix1to2[0][66] = 0.808613871647215;
   fWeightMatrix1to2[0][67] = -0.0793665203950075;
   fWeightMatrix1to2[0][68] = -3.00204478665216;
   fWeightMatrix1to2[0][69] = 0.544937149505318;
   fWeightMatrix1to2[0][70] = 0.64774573351403;
   fWeightMatrix1to2[0][71] = 0.710982381674771;
   fWeightMatrix1to2[0][72] = 0.13410526645391;
   fWeightMatrix1to2[0][73] = -0.052237124349945;
   fWeightMatrix1to2[0][74] = -0.918181860970632;
   fWeightMatrix1to2[0][75] = -0.162912925018244;
   fWeightMatrix1to2[0][76] = 0.300553335191049;
   fWeightMatrix1to2[0][77] = 0.0180042804454616;
   fWeightMatrix1to2[0][78] = -0.597829089778918;
   fWeightMatrix1to2[0][79] = 0.404420208649538;
   fWeightMatrix1to2[0][80] = -0.177330561042259;
   fWeightMatrix1to2[0][81] = 0.836348318024606;
   fWeightMatrix1to2[0][82] = 2.52801264466211;
   fWeightMatrix1to2[0][83] = 0.0406140716832047;
   fWeightMatrix1to2[0][84] = -0.180327155644808;
   fWeightMatrix1to2[0][85] = -0.035339258666154;
   fWeightMatrix1to2[0][86] = 1.0947204137113;
   fWeightMatrix1to2[0][87] = -1.53765115378949;
   fWeightMatrix1to2[0][88] = 0.760403595621931;
   fWeightMatrix1to2[0][89] = 0.276804496830348;
   fWeightMatrix1to2[0][90] = -0.177138948132797;
   fWeightMatrix1to2[0][91] = 1.5176694441071;
   fWeightMatrix1to2[0][92] = -0.79598379943146;
   fWeightMatrix1to2[0][93] = 0.0134994001230042;
   fWeightMatrix1to2[0][94] = 1.12472185246551;
   fWeightMatrix1to2[0][95] = -0.0605025490737381;
   fWeightMatrix1to2[0][96] = 0.0720792898367952;
   fWeightMatrix1to2[0][97] = 0.243666649843165;
   fWeightMatrix1to2[0][98] = 0.599047455737653;
   fWeightMatrix1to2[0][99] = 2.10034454977636;
   fWeightMatrix1to2[0][100] = 0.234721124264056;
   fWeightMatrix1to2[0][101] = -0.245861174714748;
   fWeightMatrix1to2[0][102] = 1.61677996937634;
   fWeightMatrix1to2[0][103] = 1.63001595027345;
   fWeightMatrix1to2[0][104] = 0.151881468210405;
   fWeightMatrix1to2[0][105] = 0.270575109199737;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 251;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 226;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 187;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 226;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 3;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 4;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 4;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 6;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 8;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 8;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
