// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/08       [393736]
Creator        : aocampor
Date           : Sat May  9 23:01:10 2015
Host           : Linux DaMachine 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/aocampor/DiabeticRetinophaty/macros
Training events: 2000000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+20" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
Red                           Red                           Red                           Red                                                             'F'    [0,255]
Green                         Green                         Green                         Green                                                           'F'    [0,255]
Blue                          Blue                          Blue                          Blue                                                            'F'    [0,255]
GreenOverRed                  GreenOverRed                  GreenOverRed                  GreenOverRed                                                    'F'    [0,40]
BlueOverRed                   BlueOverRed                   BlueOverRed                   BlueOverRed                                                     'F'    [0,53]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Red", "Green", "Blue", "GreenOverRed", "BlueOverRed" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[26][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][26];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 26; fWeights[1] = new double[26]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -3.75405920687818;
   fWeightMatrix0to1[1][0] = -4.13747102817932;
   fWeightMatrix0to1[2][0] = -0.872092753412412;
   fWeightMatrix0to1[3][0] = 14.3057733755033;
   fWeightMatrix0to1[4][0] = -9.93218681972726;
   fWeightMatrix0to1[5][0] = -0.827772730190251;
   fWeightMatrix0to1[6][0] = -5.29690626482067;
   fWeightMatrix0to1[7][0] = 8.19597697844624;
   fWeightMatrix0to1[8][0] = -4.49220497825869;
   fWeightMatrix0to1[9][0] = -8.7643354628423;
   fWeightMatrix0to1[10][0] = -0.415325904336733;
   fWeightMatrix0to1[11][0] = -1.9099979793883;
   fWeightMatrix0to1[12][0] = -7.85611184406751;
   fWeightMatrix0to1[13][0] = -3.1427982249831;
   fWeightMatrix0to1[14][0] = -11.0138159438277;
   fWeightMatrix0to1[15][0] = -0.0465390287302673;
   fWeightMatrix0to1[16][0] = -3.83117196471347;
   fWeightMatrix0to1[17][0] = 2.27889708326511;
   fWeightMatrix0to1[18][0] = -0.488360069691393;
   fWeightMatrix0to1[19][0] = 16.6937460765637;
   fWeightMatrix0to1[20][0] = -9.31326389170255;
   fWeightMatrix0to1[21][0] = -5.77706859996743;
   fWeightMatrix0to1[22][0] = -0.601565931575075;
   fWeightMatrix0to1[23][0] = 5.05600408416873;
   fWeightMatrix0to1[24][0] = -2.51353820968222;
   fWeightMatrix0to1[0][1] = -3.52095782854981;
   fWeightMatrix0to1[1][1] = 5.77916424459243;
   fWeightMatrix0to1[2][1] = 6.44178828833814;
   fWeightMatrix0to1[3][1] = -16.3452856060206;
   fWeightMatrix0to1[4][1] = 16.9177792203434;
   fWeightMatrix0to1[5][1] = 0.934626703217021;
   fWeightMatrix0to1[6][1] = 11.750321378853;
   fWeightMatrix0to1[7][1] = -6.40059670886063;
   fWeightMatrix0to1[8][1] = -20.1791100991053;
   fWeightMatrix0to1[9][1] = -0.262927700140975;
   fWeightMatrix0to1[10][1] = 0.817849033449291;
   fWeightMatrix0to1[11][1] = -2.59311466602067;
   fWeightMatrix0to1[12][1] = 20.0749073286615;
   fWeightMatrix0to1[13][1] = -10.7867718668402;
   fWeightMatrix0to1[14][1] = 4.49746305912102;
   fWeightMatrix0to1[15][1] = 1.41895535208115;
   fWeightMatrix0to1[16][1] = 1.03093025814398;
   fWeightMatrix0to1[17][1] = 5.16110268081473;
   fWeightMatrix0to1[18][1] = -6.84476862777074;
   fWeightMatrix0to1[19][1] = -13.5465056303729;
   fWeightMatrix0to1[20][1] = -1.87435946659156;
   fWeightMatrix0to1[21][1] = 6.61237710598366;
   fWeightMatrix0to1[22][1] = 1.21588333861616;
   fWeightMatrix0to1[23][1] = -4.94528366010258;
   fWeightMatrix0to1[24][1] = -0.823522199035546;
   fWeightMatrix0to1[0][2] = 17.3832869658207;
   fWeightMatrix0to1[1][2] = 1.51659167246116;
   fWeightMatrix0to1[2][2] = -14.3647232364257;
   fWeightMatrix0to1[3][2] = 6.47725635080893;
   fWeightMatrix0to1[4][2] = -8.09057946598891;
   fWeightMatrix0to1[5][2] = -0.609767796485035;
   fWeightMatrix0to1[6][2] = -18.5529446246839;
   fWeightMatrix0to1[7][2] = -13.5015213206332;
   fWeightMatrix0to1[8][2] = 28.7141616171979;
   fWeightMatrix0to1[9][2] = 8.74380086554974;
   fWeightMatrix0to1[10][2] = -2.6462484165603;
   fWeightMatrix0to1[11][2] = 2.56741105263471;
   fWeightMatrix0to1[12][2] = -2.94994958899458;
   fWeightMatrix0to1[13][2] = 11.5947694039314;
   fWeightMatrix0to1[14][2] = 9.42642829056964;
   fWeightMatrix0to1[15][2] = 0.352922549968518;
   fWeightMatrix0to1[16][2] = 5.26648425925911;
   fWeightMatrix0to1[17][2] = -13.05889803509;
   fWeightMatrix0to1[18][2] = 16.2132228749782;
   fWeightMatrix0to1[19][2] = -13.1711885641339;
   fWeightMatrix0to1[20][2] = -7.85097063937526;
   fWeightMatrix0to1[21][2] = -0.870402558760786;
   fWeightMatrix0to1[22][2] = 8.85446216705388;
   fWeightMatrix0to1[23][2] = 10.9343978915809;
   fWeightMatrix0to1[24][2] = 4.9478514529147;
   fWeightMatrix0to1[0][3] = 1.18648030554837;
   fWeightMatrix0to1[1][3] = 0.328890756015164;
   fWeightMatrix0to1[2][3] = -0.386088013025963;
   fWeightMatrix0to1[3][3] = 2.75155525501875;
   fWeightMatrix0to1[4][3] = 7.07781752654086;
   fWeightMatrix0to1[5][3] = 2.45913298955609;
   fWeightMatrix0to1[6][3] = 3.22775188289455;
   fWeightMatrix0to1[7][3] = 5.40155219150939;
   fWeightMatrix0to1[8][3] = -1.15068470421875;
   fWeightMatrix0to1[9][3] = -4.95776615103451;
   fWeightMatrix0to1[10][3] = 3.16531894457817;
   fWeightMatrix0to1[11][3] = 2.8474027179554;
   fWeightMatrix0to1[12][3] = -1.63176518862045;
   fWeightMatrix0to1[13][3] = -1.87390996875079;
   fWeightMatrix0to1[14][3] = 2.01447105383548;
   fWeightMatrix0to1[15][3] = 1.5339390639457;
   fWeightMatrix0to1[16][3] = 0.820237516846667;
   fWeightMatrix0to1[17][3] = 5.17776971599012;
   fWeightMatrix0to1[18][3] = -0.835856465242188;
   fWeightMatrix0to1[19][3] = 3.20568304933012;
   fWeightMatrix0to1[20][3] = 8.02072661740666;
   fWeightMatrix0to1[21][3] = 0.854270146117679;
   fWeightMatrix0to1[22][3] = -1.62587616780523;
   fWeightMatrix0to1[23][3] = -0.2673447945364;
   fWeightMatrix0to1[24][3] = 0.0911731415970585;
   fWeightMatrix0to1[0][4] = 0.207179611184515;
   fWeightMatrix0to1[1][4] = 0.458567490100028;
   fWeightMatrix0to1[2][4] = 1.1917633564783;
   fWeightMatrix0to1[3][4] = 3.48955374620242;
   fWeightMatrix0to1[4][4] = -0.813187737573871;
   fWeightMatrix0to1[5][4] = 2.70129322384305;
   fWeightMatrix0to1[6][4] = -2.49780895825087;
   fWeightMatrix0to1[7][4] = 5.48285549587676;
   fWeightMatrix0to1[8][4] = -1.94627651739608;
   fWeightMatrix0to1[9][4] = 0.00309222806494306;
   fWeightMatrix0to1[10][4] = 1.26295910058343;
   fWeightMatrix0to1[11][4] = 1.41842535353446;
   fWeightMatrix0to1[12][4] = -0.273928775732513;
   fWeightMatrix0to1[13][4] = 2.41845114324214;
   fWeightMatrix0to1[14][4] = -0.0512525971213928;
   fWeightMatrix0to1[15][4] = 3.73479738772546;
   fWeightMatrix0to1[16][4] = 0.704568988012891;
   fWeightMatrix0to1[17][4] = 1.37384087505867;
   fWeightMatrix0to1[18][4] = 1.53038541329868;
   fWeightMatrix0to1[19][4] = 4.30398648967727;
   fWeightMatrix0to1[20][4] = 2.86283113594252;
   fWeightMatrix0to1[21][4] = 0.78126176791759;
   fWeightMatrix0to1[22][4] = -0.461123735237728;
   fWeightMatrix0to1[23][4] = 3.34927486381213;
   fWeightMatrix0to1[24][4] = 0.991734056479722;
   fWeightMatrix0to1[0][5] = -1.68294555093362;
   fWeightMatrix0to1[1][5] = -2.36750201876061;
   fWeightMatrix0to1[2][5] = -8.99348611311652;
   fWeightMatrix0to1[3][5] = -2.30582568483847;
   fWeightMatrix0to1[4][5] = 6.4717840442889;
   fWeightMatrix0to1[5][5] = -0.890503757163671;
   fWeightMatrix0to1[6][5] = -10.7087561253364;
   fWeightMatrix0to1[7][5] = -4.74876104215998;
   fWeightMatrix0to1[8][5] = 0.290503811090871;
   fWeightMatrix0to1[9][5] = -6.98565399904318;
   fWeightMatrix0to1[10][5] = -1.91908636849402;
   fWeightMatrix0to1[11][5] = 0.247868662961389;
   fWeightMatrix0to1[12][5] = -2.05351165083636;
   fWeightMatrix0to1[13][5] = -2.63167137326125;
   fWeightMatrix0to1[14][5] = 4.16029401952345;
   fWeightMatrix0to1[15][5] = -0.153286369723658;
   fWeightMatrix0to1[16][5] = -1.86413968364344;
   fWeightMatrix0to1[17][5] = -4.04009823317889;
   fWeightMatrix0to1[18][5] = -1.46140000255431;
   fWeightMatrix0to1[19][5] = -6.40785419556803;
   fWeightMatrix0to1[20][5] = -5.43625281212823;
   fWeightMatrix0to1[21][5] = -0.689868256397144;
   fWeightMatrix0to1[22][5] = -0.615312460248706;
   fWeightMatrix0to1[23][5] = -1.79170831360096;
   fWeightMatrix0to1[24][5] = -1.48894739258463;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.862266918431;
   fWeightMatrix1to2[0][1] = -3.45969104434098;
   fWeightMatrix1to2[0][2] = -6.51927240783333;
   fWeightMatrix1to2[0][3] = -1.00804432772521;
   fWeightMatrix1to2[0][4] = 0.811828884342642;
   fWeightMatrix1to2[0][5] = -1.90605422811766;
   fWeightMatrix1to2[0][6] = 3.19887004275665;
   fWeightMatrix1to2[0][7] = 1.3422164556184;
   fWeightMatrix1to2[0][8] = 0.814660274962021;
   fWeightMatrix1to2[0][9] = -3.36079893477254;
   fWeightMatrix1to2[0][10] = -1.59884799569486;
   fWeightMatrix1to2[0][11] = -3.662812510459;
   fWeightMatrix1to2[0][12] = -0.504503554803712;
   fWeightMatrix1to2[0][13] = 2.44947343005135;
   fWeightMatrix1to2[0][14] = -1.03267388814639;
   fWeightMatrix1to2[0][15] = -1.9061809102477;
   fWeightMatrix1to2[0][16] = 3.42823730429124;
   fWeightMatrix1to2[0][17] = 2.79162053633311;
   fWeightMatrix1to2[0][18] = -2.23800046089965;
   fWeightMatrix1to2[0][19] = 0.64455497433052;
   fWeightMatrix1to2[0][20] = -0.866987491421957;
   fWeightMatrix1to2[0][21] = 3.07973155032804;
   fWeightMatrix1to2[0][22] = 0.445329334516547;
   fWeightMatrix1to2[0][23] = 0.990813507534262;
   fWeightMatrix1to2[0][24] = 2.91594467226774;
   fWeightMatrix1to2[0][25] = 0.131418639606789;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 255;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 255;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 255;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 255;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 255;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 255;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 255;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 255;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 255;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 33;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 40;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 40;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 48;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 53;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 53;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
